// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module conv_2d_cl_ss_ap_fixed_ap_fixed_16_4_5_3_0_config2_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        data_V_V_dout,
        data_V_V_empty_n,
        data_V_V_read,
        res_V_V_din,
        res_V_V_full_n,
        res_V_V_write
);

parameter    ap_ST_fsm_state1 = 24'd1;
parameter    ap_ST_fsm_state2 = 24'd2;
parameter    ap_ST_fsm_state3 = 24'd4;
parameter    ap_ST_fsm_state4 = 24'd8;
parameter    ap_ST_fsm_pp0_stage0 = 24'd16;
parameter    ap_ST_fsm_state7 = 24'd32;
parameter    ap_ST_fsm_state8 = 24'd64;
parameter    ap_ST_fsm_state9 = 24'd128;
parameter    ap_ST_fsm_state10 = 24'd256;
parameter    ap_ST_fsm_state11 = 24'd512;
parameter    ap_ST_fsm_state12 = 24'd1024;
parameter    ap_ST_fsm_state13 = 24'd2048;
parameter    ap_ST_fsm_state14 = 24'd4096;
parameter    ap_ST_fsm_state15 = 24'd8192;
parameter    ap_ST_fsm_state16 = 24'd16384;
parameter    ap_ST_fsm_state17 = 24'd32768;
parameter    ap_ST_fsm_state18 = 24'd65536;
parameter    ap_ST_fsm_state19 = 24'd131072;
parameter    ap_ST_fsm_state20 = 24'd262144;
parameter    ap_ST_fsm_state21 = 24'd524288;
parameter    ap_ST_fsm_state22 = 24'd1048576;
parameter    ap_ST_fsm_state23 = 24'd2097152;
parameter    ap_ST_fsm_state24 = 24'd4194304;
parameter    ap_ST_fsm_state25 = 24'd8388608;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [15:0] data_V_V_dout;
input   data_V_V_empty_n;
output   data_V_V_read;
output  [15:0] res_V_V_din;
input   res_V_V_full_n;
output   res_V_V_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg data_V_V_read;
reg res_V_V_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [23:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg   [4:0] layer_in_V_7_address0;
reg    layer_in_V_7_ce0;
reg    layer_in_V_7_we0;
wire  signed [15:0] layer_in_V_7_q0;
reg   [31:0] sX_2;
reg   [31:0] sY_2;
reg   [31:0] pY_2;
reg   [31:0] pX_2;
wire   [4:0] w2_V_address0;
reg    w2_V_ce0;
wire   [254:0] w2_V_q0;
reg    data_V_V_blk_n;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln315_fu_1109_p2;
reg    res_V_V_blk_n;
wire    ap_CS_fsm_state24;
reg   [23:0] acc_V_31_0_reg_671;
reg   [23:0] acc_V_30_0_reg_683;
reg   [23:0] acc_V_29_0_reg_695;
reg   [23:0] acc_V_28_0_reg_707;
reg   [23:0] acc_V_27_0_reg_719;
reg   [23:0] acc_V_26_0_reg_731;
reg   [23:0] acc_V_25_0_reg_743;
reg   [23:0] acc_V_24_0_reg_755;
reg   [23:0] acc_V_23_0_reg_767;
reg   [23:0] acc_V_22_0_reg_779;
reg   [23:0] acc_V_21_0_reg_791;
reg   [23:0] acc_V_20_0_reg_803;
reg   [23:0] acc_V_19_0_reg_815;
reg   [23:0] acc_V_18_0_reg_827;
reg   [23:0] acc_V_17_0_reg_839;
reg   [23:0] acc_V_16_0_reg_851;
reg   [23:0] acc_V_15_0_reg_863;
reg   [23:0] acc_V_14_0_reg_875;
reg   [23:0] acc_V_13_0_reg_887;
reg   [23:0] acc_V_12_0_reg_899;
reg   [23:0] acc_V_11_0_reg_911;
reg   [23:0] acc_V_10_0_reg_923;
reg   [23:0] acc_V_9_0_reg_935;
reg   [23:0] acc_V_8_0_reg_947;
reg   [23:0] acc_V_7_0_reg_959;
reg   [23:0] acc_V_6_0_reg_971;
reg   [23:0] acc_V_5_0_reg_983;
reg   [23:0] acc_V_4_0_reg_995;
reg   [23:0] acc_V_3_0_reg_1007;
reg   [23:0] acc_V_2_0_reg_1019;
reg   [23:0] acc_V_1_0_reg_1031;
reg   [23:0] acc_V_0_0_reg_1043;
reg   [4:0] in_index_reg_1055;
reg    ap_block_state1;
wire   [12:0] i_fu_1103_p2;
reg   [12:0] i_reg_2516;
wire    ap_CS_fsm_state2;
wire   [1:0] i1_fu_1115_p2;
reg    ap_block_state3;
reg   [31:0] sX_2_load_reg_2529;
wire    ap_CS_fsm_state4;
wire    grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_ready;
wire    grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_done;
wire   [0:0] icmp_ln326_fu_1130_p2;
reg   [0:0] icmp_ln326_reg_2534;
reg   [31:0] sY_2_load_reg_2539;
wire   [0:0] icmp_ln326_7_fu_1140_p2;
reg   [0:0] icmp_ln326_7_reg_2544;
reg   [31:0] pY_2_load_reg_2549;
reg   [31:0] pX_2_load_reg_2555;
wire   [0:0] and_ln326_6_fu_1198_p2;
reg   [0:0] and_ln326_6_reg_2561;
wire   [0:0] icmp_ln324_fu_1204_p2;
reg   [0:0] icmp_ln324_reg_2565;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state5_pp0_stage0_iter0;
wire    ap_block_state6_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire   [4:0] ir_fu_1210_p2;
reg    ap_enable_reg_pp0_iter0;
wire  signed [23:0] grp_fu_2097_p3;
reg    ap_enable_reg_pp0_iter1;
wire  signed [23:0] grp_fu_2105_p3;
wire  signed [23:0] grp_fu_2113_p3;
wire  signed [23:0] grp_fu_2121_p3;
wire  signed [23:0] grp_fu_2129_p3;
wire  signed [23:0] grp_fu_2137_p3;
wire  signed [23:0] grp_fu_2145_p3;
wire  signed [23:0] grp_fu_2153_p3;
wire  signed [23:0] grp_fu_2161_p3;
wire  signed [23:0] grp_fu_2169_p3;
wire  signed [23:0] grp_fu_2177_p3;
wire  signed [23:0] grp_fu_2185_p3;
wire  signed [23:0] grp_fu_2193_p3;
wire  signed [23:0] grp_fu_2201_p3;
wire  signed [23:0] grp_fu_2209_p3;
wire  signed [23:0] grp_fu_2217_p3;
wire  signed [23:0] grp_fu_2225_p3;
wire  signed [23:0] grp_fu_2233_p3;
wire  signed [23:0] grp_fu_2241_p3;
wire  signed [23:0] grp_fu_2249_p3;
wire  signed [23:0] grp_fu_2257_p3;
wire  signed [23:0] grp_fu_2265_p3;
wire  signed [23:0] grp_fu_2273_p3;
wire  signed [23:0] grp_fu_2281_p3;
wire  signed [23:0] grp_fu_2289_p3;
wire  signed [23:0] grp_fu_2297_p3;
wire  signed [23:0] grp_fu_2305_p3;
wire  signed [23:0] grp_fu_2313_p3;
wire  signed [23:0] grp_fu_2321_p3;
wire  signed [23:0] grp_fu_2329_p3;
wire  signed [23:0] grp_fu_2337_p3;
wire  signed [23:0] grp_fu_2345_p3;
reg   [15:0] trunc_ln708_77_reg_2744;
wire    ap_CS_fsm_state7;
reg   [15:0] trunc_ln708_78_reg_2749;
reg   [15:0] trunc_ln708_79_reg_2754;
reg   [15:0] trunc_ln708_80_reg_2759;
reg   [15:0] trunc_ln708_81_reg_2764;
reg   [15:0] trunc_ln708_82_reg_2769;
reg   [15:0] trunc_ln708_83_reg_2774;
reg   [15:0] trunc_ln708_84_reg_2779;
reg   [15:0] trunc_ln708_85_reg_2784;
reg   [15:0] trunc_ln708_86_reg_2789;
reg   [15:0] trunc_ln708_87_reg_2794;
reg   [15:0] trunc_ln708_88_reg_2799;
reg   [15:0] trunc_ln708_89_reg_2804;
reg   [15:0] trunc_ln708_90_reg_2809;
reg   [15:0] trunc_ln708_91_reg_2814;
reg   [15:0] trunc_ln708_92_reg_2819;
reg   [15:0] trunc_ln708_93_reg_2824;
reg   [15:0] trunc_ln708_94_reg_2829;
reg   [15:0] trunc_ln708_95_reg_2834;
reg   [15:0] trunc_ln708_96_reg_2839;
reg   [15:0] trunc_ln708_97_reg_2844;
reg   [15:0] trunc_ln708_98_reg_2849;
reg   [15:0] trunc_ln708_99_reg_2854;
reg   [15:0] trunc_ln708_100_reg_2859;
reg   [15:0] trunc_ln708_101_reg_2864;
reg   [15:0] trunc_ln708_102_reg_2869;
reg   [15:0] trunc_ln708_103_reg_2874;
reg   [15:0] trunc_ln708_104_reg_2879;
reg   [15:0] trunc_ln708_105_reg_2884;
reg   [15:0] trunc_ln708_106_reg_2889;
wire   [5:0] i_ic_fu_2000_p2;
reg   [5:0] i_ic_reg_2897;
wire    ap_CS_fsm_state23;
wire   [0:0] icmp_ln338_fu_1994_p2;
wire   [0:0] icmp_ln346_fu_2011_p2;
reg   [0:0] icmp_ln346_reg_2907;
wire   [31:0] select_ln356_fu_2078_p3;
wire   [0:0] icmp_ln350_fu_2057_p2;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state5;
reg   [1:0] tmpdata_V_address0;
reg    tmpdata_V_ce0;
reg    tmpdata_V_we0;
wire   [15:0] tmpdata_V_q0;
reg   [4:0] layer_out_i_address0;
reg    layer_out_i_ce0;
reg    layer_out_i_we0;
reg   [15:0] layer_out_i_d0;
wire   [15:0] layer_out_i_q0;
reg   [4:0] layer_out_i_address1;
reg    layer_out_i_ce1;
reg    layer_out_i_we1;
reg   [15:0] layer_out_i_d1;
wire    grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_start;
wire    grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_idle;
wire   [1:0] grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_data_V_address0;
wire    grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_data_V_ce0;
wire   [4:0] grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_output_V_address0;
wire    grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_output_V_ce0;
wire    grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_output_V_we0;
wire   [15:0] grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_output_V_d0;
reg   [12:0] i_0_i_reg_649;
wire    ap_CS_fsm_state25;
reg   [1:0] i1_0_i_reg_660;
wire   [0:0] icmp_ln313_fu_1097_p2;
wire    ap_block_pp0_stage0;
reg   [5:0] i_ic_0_i_reg_1066;
wire    ap_CS_fsm_state22;
reg   [31:0] storemerge_i_reg_1077;
reg    grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_start_reg;
reg    ap_block_state3_ignore_call0;
wire   [63:0] zext_ln317_fu_1121_p1;
wire   [63:0] zext_ln332_fu_1216_p1;
wire   [63:0] zext_ln340_fu_2006_p1;
wire   [31:0] select_ln361_fu_2032_p3;
wire   [31:0] add_ln354_fu_2062_p2;
wire   [31:0] add_ln359_fu_2016_p2;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state19;
wire    ap_CS_fsm_state20;
wire    ap_CS_fsm_state21;
wire   [30:0] tmp_7_fu_1150_p4;
wire   [30:0] tmp_8_fu_1170_p4;
wire   [0:0] icmp_ln326_8_fu_1160_p2;
wire   [0:0] icmp_ln326_9_fu_1180_p2;
wire   [0:0] and_ln326_5_fu_1192_p2;
wire   [0:0] and_ln326_fu_1186_p2;
wire  signed [15:0] sext_ln1116_fu_1226_p0;
wire  signed [7:0] trunc_ln332_fu_1222_p1;
wire  signed [7:0] tmp_126_fu_1238_p4;
wire  signed [7:0] tmp_127_fu_1252_p4;
wire  signed [7:0] tmp_128_fu_1266_p4;
wire  signed [7:0] tmp_129_fu_1280_p4;
wire  signed [7:0] tmp_130_fu_1294_p4;
wire  signed [7:0] tmp_131_fu_1308_p4;
wire  signed [7:0] tmp_132_fu_1322_p4;
wire  signed [7:0] tmp_133_fu_1336_p4;
wire  signed [7:0] tmp_134_fu_1350_p4;
wire  signed [7:0] tmp_135_fu_1364_p4;
wire  signed [7:0] tmp_136_fu_1378_p4;
wire  signed [7:0] tmp_137_fu_1392_p4;
wire  signed [7:0] tmp_138_fu_1406_p4;
wire  signed [7:0] tmp_139_fu_1420_p4;
wire  signed [7:0] tmp_140_fu_1434_p4;
wire  signed [7:0] tmp_141_fu_1448_p4;
wire  signed [7:0] tmp_142_fu_1462_p4;
wire  signed [7:0] tmp_143_fu_1476_p4;
wire  signed [7:0] tmp_144_fu_1490_p4;
wire  signed [7:0] tmp_145_fu_1504_p4;
wire  signed [7:0] tmp_146_fu_1518_p4;
wire  signed [7:0] tmp_147_fu_1532_p4;
wire  signed [7:0] tmp_148_fu_1546_p4;
wire  signed [7:0] tmp_149_fu_1560_p4;
wire  signed [7:0] tmp_150_fu_1574_p4;
wire  signed [7:0] tmp_151_fu_1588_p4;
wire  signed [7:0] tmp_152_fu_1602_p4;
wire  signed [7:0] tmp_153_fu_1616_p4;
wire  signed [7:0] tmp_154_fu_1630_p4;
wire  signed [7:0] tmp_155_fu_1644_p4;
wire  signed [6:0] tmp_4_fu_1658_p4;
wire   [31:0] add_ln361_fu_2027_p2;
wire   [31:0] add_ln356_fu_2073_p2;
wire  signed [15:0] grp_fu_2097_p1;
wire  signed [23:0] sext_ln1116_fu_1226_p1;
wire  signed [15:0] grp_fu_2105_p1;
wire  signed [15:0] grp_fu_2113_p1;
wire  signed [15:0] grp_fu_2121_p1;
wire  signed [15:0] grp_fu_2129_p1;
wire  signed [15:0] grp_fu_2137_p1;
wire  signed [15:0] grp_fu_2145_p1;
wire  signed [15:0] grp_fu_2153_p1;
wire  signed [15:0] grp_fu_2161_p1;
wire  signed [15:0] grp_fu_2169_p1;
wire  signed [15:0] grp_fu_2177_p1;
wire  signed [15:0] grp_fu_2185_p1;
wire  signed [15:0] grp_fu_2193_p1;
wire  signed [15:0] grp_fu_2201_p1;
wire  signed [15:0] grp_fu_2209_p1;
wire  signed [15:0] grp_fu_2217_p1;
wire  signed [15:0] grp_fu_2225_p1;
wire  signed [15:0] grp_fu_2233_p1;
wire  signed [15:0] grp_fu_2241_p1;
wire  signed [15:0] grp_fu_2249_p1;
wire  signed [15:0] grp_fu_2257_p1;
wire  signed [15:0] grp_fu_2265_p1;
wire  signed [15:0] grp_fu_2273_p1;
wire  signed [15:0] grp_fu_2281_p1;
wire  signed [15:0] grp_fu_2289_p1;
wire  signed [15:0] grp_fu_2297_p1;
wire  signed [15:0] grp_fu_2305_p1;
wire  signed [15:0] grp_fu_2313_p1;
wire  signed [15:0] grp_fu_2321_p1;
wire  signed [15:0] grp_fu_2329_p1;
wire  signed [15:0] grp_fu_2337_p1;
reg   [23:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_654;
reg    ap_condition_656;
reg    ap_condition_470;
reg    ap_condition_592;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 24'd1;
#0 sX_2 = 32'd0;
#0 sY_2 = 32'd0;
#0 pY_2 = 32'd0;
#0 pX_2 = 32'd0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_start_reg = 1'b0;
end

conv_2d_cl_ss_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_layedEe #(
    .DataWidth( 16 ),
    .AddressRange( 27 ),
    .AddressWidth( 5 ))
layer_in_V_7_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(layer_in_V_7_address0),
    .ce0(layer_in_V_7_ce0),
    .we0(layer_in_V_7_we0),
    .d0(grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_output_V_d0),
    .q0(layer_in_V_7_q0)
);

conv_2d_cl_ss_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_w2_V #(
    .DataWidth( 255 ),
    .AddressRange( 27 ),
    .AddressWidth( 5 ))
w2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w2_V_address0),
    .ce0(w2_V_ce0),
    .q0(w2_V_q0)
);

conv_2d_cl_ss_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_tmpdeOg #(
    .DataWidth( 16 ),
    .AddressRange( 3 ),
    .AddressWidth( 2 ))
tmpdata_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(tmpdata_V_address0),
    .ce0(tmpdata_V_ce0),
    .we0(tmpdata_V_we0),
    .d0(data_V_V_dout),
    .q0(tmpdata_V_q0)
);

conv_2d_cl_ss_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_layefYi #(
    .DataWidth( 16 ),
    .AddressRange( 32 ),
    .AddressWidth( 5 ))
layer_out_i_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(layer_out_i_address0),
    .ce0(layer_out_i_ce0),
    .we0(layer_out_i_we0),
    .d0(layer_out_i_d0),
    .q0(layer_out_i_q0),
    .address1(layer_out_i_address1),
    .ce1(layer_out_i_ce1),
    .we1(layer_out_i_we1),
    .d1(layer_out_i_d1)
);

cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_start),
    .ap_done(grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_done),
    .ap_idle(grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_idle),
    .ap_ready(grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_ready),
    .data_V_address0(grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_data_V_address0),
    .data_V_ce0(grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_data_V_ce0),
    .data_V_q0(tmpdata_V_q0),
    .output_V_address0(grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_output_V_address0),
    .output_V_ce0(grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_output_V_ce0),
    .output_V_we0(grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_output_V_we0),
    .output_V_d0(grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_output_V_d0),
    .output_V_q0(layer_in_V_7_q0)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U8(
    .din0(trunc_ln332_fu_1222_p1),
    .din1(grp_fu_2097_p1),
    .din2(acc_V_0_0_reg_1043),
    .dout(grp_fu_2097_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U9(
    .din0(tmp_126_fu_1238_p4),
    .din1(grp_fu_2105_p1),
    .din2(acc_V_1_0_reg_1031),
    .dout(grp_fu_2105_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U10(
    .din0(tmp_127_fu_1252_p4),
    .din1(grp_fu_2113_p1),
    .din2(acc_V_2_0_reg_1019),
    .dout(grp_fu_2113_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U11(
    .din0(tmp_128_fu_1266_p4),
    .din1(grp_fu_2121_p1),
    .din2(acc_V_3_0_reg_1007),
    .dout(grp_fu_2121_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U12(
    .din0(tmp_129_fu_1280_p4),
    .din1(grp_fu_2129_p1),
    .din2(acc_V_4_0_reg_995),
    .dout(grp_fu_2129_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U13(
    .din0(tmp_130_fu_1294_p4),
    .din1(grp_fu_2137_p1),
    .din2(acc_V_5_0_reg_983),
    .dout(grp_fu_2137_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U14(
    .din0(tmp_131_fu_1308_p4),
    .din1(grp_fu_2145_p1),
    .din2(acc_V_6_0_reg_971),
    .dout(grp_fu_2145_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U15(
    .din0(tmp_132_fu_1322_p4),
    .din1(grp_fu_2153_p1),
    .din2(acc_V_7_0_reg_959),
    .dout(grp_fu_2153_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U16(
    .din0(tmp_133_fu_1336_p4),
    .din1(grp_fu_2161_p1),
    .din2(acc_V_8_0_reg_947),
    .dout(grp_fu_2161_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U17(
    .din0(tmp_134_fu_1350_p4),
    .din1(grp_fu_2169_p1),
    .din2(acc_V_9_0_reg_935),
    .dout(grp_fu_2169_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U18(
    .din0(tmp_135_fu_1364_p4),
    .din1(grp_fu_2177_p1),
    .din2(acc_V_10_0_reg_923),
    .dout(grp_fu_2177_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U19(
    .din0(tmp_136_fu_1378_p4),
    .din1(grp_fu_2185_p1),
    .din2(acc_V_11_0_reg_911),
    .dout(grp_fu_2185_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U20(
    .din0(tmp_137_fu_1392_p4),
    .din1(grp_fu_2193_p1),
    .din2(acc_V_12_0_reg_899),
    .dout(grp_fu_2193_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U21(
    .din0(tmp_138_fu_1406_p4),
    .din1(grp_fu_2201_p1),
    .din2(acc_V_13_0_reg_887),
    .dout(grp_fu_2201_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U22(
    .din0(tmp_139_fu_1420_p4),
    .din1(grp_fu_2209_p1),
    .din2(acc_V_14_0_reg_875),
    .dout(grp_fu_2209_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U23(
    .din0(tmp_140_fu_1434_p4),
    .din1(grp_fu_2217_p1),
    .din2(acc_V_15_0_reg_863),
    .dout(grp_fu_2217_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U24(
    .din0(tmp_141_fu_1448_p4),
    .din1(grp_fu_2225_p1),
    .din2(acc_V_16_0_reg_851),
    .dout(grp_fu_2225_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U25(
    .din0(tmp_142_fu_1462_p4),
    .din1(grp_fu_2233_p1),
    .din2(acc_V_17_0_reg_839),
    .dout(grp_fu_2233_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U26(
    .din0(tmp_143_fu_1476_p4),
    .din1(grp_fu_2241_p1),
    .din2(acc_V_18_0_reg_827),
    .dout(grp_fu_2241_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U27(
    .din0(tmp_144_fu_1490_p4),
    .din1(grp_fu_2249_p1),
    .din2(acc_V_19_0_reg_815),
    .dout(grp_fu_2249_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U28(
    .din0(tmp_145_fu_1504_p4),
    .din1(grp_fu_2257_p1),
    .din2(acc_V_20_0_reg_803),
    .dout(grp_fu_2257_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U29(
    .din0(tmp_146_fu_1518_p4),
    .din1(grp_fu_2265_p1),
    .din2(acc_V_21_0_reg_791),
    .dout(grp_fu_2265_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U30(
    .din0(tmp_147_fu_1532_p4),
    .din1(grp_fu_2273_p1),
    .din2(acc_V_22_0_reg_779),
    .dout(grp_fu_2273_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U31(
    .din0(tmp_148_fu_1546_p4),
    .din1(grp_fu_2281_p1),
    .din2(acc_V_23_0_reg_767),
    .dout(grp_fu_2281_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U32(
    .din0(tmp_149_fu_1560_p4),
    .din1(grp_fu_2289_p1),
    .din2(acc_V_24_0_reg_755),
    .dout(grp_fu_2289_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U33(
    .din0(tmp_150_fu_1574_p4),
    .din1(grp_fu_2297_p1),
    .din2(acc_V_25_0_reg_743),
    .dout(grp_fu_2297_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U34(
    .din0(tmp_151_fu_1588_p4),
    .din1(grp_fu_2305_p1),
    .din2(acc_V_26_0_reg_731),
    .dout(grp_fu_2305_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U35(
    .din0(tmp_152_fu_1602_p4),
    .din1(grp_fu_2313_p1),
    .din2(acc_V_27_0_reg_719),
    .dout(grp_fu_2313_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U36(
    .din0(tmp_153_fu_1616_p4),
    .din1(grp_fu_2321_p1),
    .din2(acc_V_28_0_reg_707),
    .dout(grp_fu_2321_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U37(
    .din0(tmp_154_fu_1630_p4),
    .din1(grp_fu_2329_p1),
    .din2(acc_V_29_0_reg_695),
    .dout(grp_fu_2329_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U38(
    .din0(tmp_155_fu_1644_p4),
    .din1(grp_fu_2337_p1),
    .din2(acc_V_30_0_reg_683),
    .dout(grp_fu_2337_p3)
);

myproject_mac_muladd_7s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 7 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_7s_16s_24ns_24_1_1_U39(
    .din0(tmp_4_fu_1658_p4),
    .din1(layer_in_V_7_q0),
    .din2(acc_V_31_0_reg_671),
    .dout(grp_fu_2345_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln313_fu_1097_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state5) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'd1 == and_ln326_6_fu_1198_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state5))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state5);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((1'd1 == and_ln326_6_fu_1198_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_start_reg <= 1'b0;
    end else begin
        if ((~((icmp_ln315_fu_1109_p2 == 1'd0) & (data_V_V_empty_n == 1'b0)) & (icmp_ln315_fu_1109_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
            grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_start_reg <= 1'b1;
        end else if ((grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_ready == 1'b1)) begin
            grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2565 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_0_0_reg_1043 <= grp_fu_2097_p3;
    end else if (((1'd1 == and_ln326_6_fu_1198_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_0_0_reg_1043 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2565 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_10_0_reg_923 <= grp_fu_2177_p3;
    end else if (((1'd1 == and_ln326_6_fu_1198_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_10_0_reg_923 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2565 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_11_0_reg_911 <= grp_fu_2185_p3;
    end else if (((1'd1 == and_ln326_6_fu_1198_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_11_0_reg_911 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2565 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_12_0_reg_899 <= grp_fu_2193_p3;
    end else if (((1'd1 == and_ln326_6_fu_1198_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_12_0_reg_899 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2565 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_13_0_reg_887 <= grp_fu_2201_p3;
    end else if (((1'd1 == and_ln326_6_fu_1198_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_13_0_reg_887 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2565 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_14_0_reg_875 <= grp_fu_2209_p3;
    end else if (((1'd1 == and_ln326_6_fu_1198_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_14_0_reg_875 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2565 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_15_0_reg_863 <= grp_fu_2217_p3;
    end else if (((1'd1 == and_ln326_6_fu_1198_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_15_0_reg_863 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2565 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_16_0_reg_851 <= grp_fu_2225_p3;
    end else if (((1'd1 == and_ln326_6_fu_1198_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_16_0_reg_851 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2565 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_17_0_reg_839 <= grp_fu_2233_p3;
    end else if (((1'd1 == and_ln326_6_fu_1198_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_17_0_reg_839 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2565 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_18_0_reg_827 <= grp_fu_2241_p3;
    end else if (((1'd1 == and_ln326_6_fu_1198_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_18_0_reg_827 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2565 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_19_0_reg_815 <= grp_fu_2249_p3;
    end else if (((1'd1 == and_ln326_6_fu_1198_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_19_0_reg_815 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2565 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_1_0_reg_1031 <= grp_fu_2105_p3;
    end else if (((1'd1 == and_ln326_6_fu_1198_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_1_0_reg_1031 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2565 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_20_0_reg_803 <= grp_fu_2257_p3;
    end else if (((1'd1 == and_ln326_6_fu_1198_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_20_0_reg_803 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2565 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_21_0_reg_791 <= grp_fu_2265_p3;
    end else if (((1'd1 == and_ln326_6_fu_1198_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_21_0_reg_791 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2565 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_22_0_reg_779 <= grp_fu_2273_p3;
    end else if (((1'd1 == and_ln326_6_fu_1198_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_22_0_reg_779 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2565 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_23_0_reg_767 <= grp_fu_2281_p3;
    end else if (((1'd1 == and_ln326_6_fu_1198_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_23_0_reg_767 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2565 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_24_0_reg_755 <= grp_fu_2289_p3;
    end else if (((1'd1 == and_ln326_6_fu_1198_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_24_0_reg_755 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2565 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_25_0_reg_743 <= grp_fu_2297_p3;
    end else if (((1'd1 == and_ln326_6_fu_1198_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_25_0_reg_743 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2565 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_26_0_reg_731 <= grp_fu_2305_p3;
    end else if (((1'd1 == and_ln326_6_fu_1198_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_26_0_reg_731 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2565 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_27_0_reg_719 <= grp_fu_2313_p3;
    end else if (((1'd1 == and_ln326_6_fu_1198_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_27_0_reg_719 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2565 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_28_0_reg_707 <= grp_fu_2321_p3;
    end else if (((1'd1 == and_ln326_6_fu_1198_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_28_0_reg_707 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2565 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_29_0_reg_695 <= grp_fu_2329_p3;
    end else if (((1'd1 == and_ln326_6_fu_1198_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_29_0_reg_695 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2565 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_2_0_reg_1019 <= grp_fu_2113_p3;
    end else if (((1'd1 == and_ln326_6_fu_1198_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_2_0_reg_1019 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2565 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_30_0_reg_683 <= grp_fu_2337_p3;
    end else if (((1'd1 == and_ln326_6_fu_1198_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_30_0_reg_683 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2565 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_31_0_reg_671 <= grp_fu_2345_p3;
    end else if (((1'd1 == and_ln326_6_fu_1198_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_31_0_reg_671 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2565 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_3_0_reg_1007 <= grp_fu_2121_p3;
    end else if (((1'd1 == and_ln326_6_fu_1198_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_3_0_reg_1007 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2565 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_4_0_reg_995 <= grp_fu_2129_p3;
    end else if (((1'd1 == and_ln326_6_fu_1198_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_4_0_reg_995 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2565 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_5_0_reg_983 <= grp_fu_2137_p3;
    end else if (((1'd1 == and_ln326_6_fu_1198_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_5_0_reg_983 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2565 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_6_0_reg_971 <= grp_fu_2145_p3;
    end else if (((1'd1 == and_ln326_6_fu_1198_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_6_0_reg_971 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2565 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_7_0_reg_959 <= grp_fu_2153_p3;
    end else if (((1'd1 == and_ln326_6_fu_1198_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_7_0_reg_959 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2565 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_8_0_reg_947 <= grp_fu_2161_p3;
    end else if (((1'd1 == and_ln326_6_fu_1198_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_8_0_reg_947 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_reg_2565 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_V_9_0_reg_935 <= grp_fu_2169_p3;
    end else if (((1'd1 == and_ln326_6_fu_1198_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_9_0_reg_935 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((icmp_ln315_fu_1109_p2 == 1'd0) & (data_V_V_empty_n == 1'b0)) & (icmp_ln315_fu_1109_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        i1_0_i_reg_660 <= i1_fu_1115_p2;
    end else if (((icmp_ln313_fu_1097_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        i1_0_i_reg_660 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        i_0_i_reg_649 <= i_reg_2516;
    end else if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_0_i_reg_649 <= 13'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state24))) begin
        i_ic_0_i_reg_1066 <= i_ic_reg_2897;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        i_ic_0_i_reg_1066 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln324_fu_1204_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_index_reg_1055 <= ir_fu_1210_p2;
    end else if (((1'd1 == and_ln326_6_fu_1198_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        in_index_reg_1055 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        if ((1'b1 == ap_condition_656)) begin
            pX_2 <= 32'd0;
        end else if ((1'b1 == ap_condition_654)) begin
            pX_2 <= add_ln359_fu_2016_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        if ((1'b1 == ap_condition_592)) begin
            pY_2 <= 32'd0;
        end else if ((1'b1 == ap_condition_470)) begin
            pY_2 <= add_ln354_fu_2062_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        if ((1'b1 == ap_condition_656)) begin
            sX_2 <= 32'd0;
        end else if ((1'b1 == ap_condition_654)) begin
            sX_2 <= select_ln361_fu_2032_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        if ((1'b1 == ap_condition_592)) begin
            storemerge_i_reg_1077 <= 32'd0;
        end else if ((1'b1 == ap_condition_470)) begin
            storemerge_i_reg_1077 <= select_ln356_fu_2078_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        and_ln326_6_reg_2561 <= and_ln326_6_fu_1198_p2;
        icmp_ln326_7_reg_2544 <= icmp_ln326_7_fu_1140_p2;
        icmp_ln326_reg_2534 <= icmp_ln326_fu_1130_p2;
        pX_2_load_reg_2555 <= pX_2;
        pY_2_load_reg_2549 <= pY_2;
        sX_2_load_reg_2529 <= sX_2;
        sY_2_load_reg_2539 <= sY_2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln326_6_reg_2561) & (1'b1 == ap_CS_fsm_state23))) begin
        i_ic_reg_2897 <= i_ic_fu_2000_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_reg_2516 <= i_fu_1103_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln324_reg_2565 <= icmp_ln324_fu_1204_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state23) & ((1'd0 == and_ln326_6_reg_2561) | (icmp_ln338_fu_1994_p2 == 1'd1)))) begin
        icmp_ln346_reg_2907 <= icmp_ln346_fu_2011_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln346_reg_2907 == 1'd1) & (1'b1 == ap_CS_fsm_state25))) begin
        sY_2 <= storemerge_i_reg_1077;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        trunc_ln708_100_reg_2859 <= {{acc_V_25_0_reg_743[22:7]}};
        trunc_ln708_101_reg_2864 <= {{acc_V_26_0_reg_731[22:7]}};
        trunc_ln708_102_reg_2869 <= {{acc_V_27_0_reg_719[22:7]}};
        trunc_ln708_103_reg_2874 <= {{acc_V_28_0_reg_707[22:7]}};
        trunc_ln708_104_reg_2879 <= {{acc_V_29_0_reg_695[22:7]}};
        trunc_ln708_105_reg_2884 <= {{acc_V_30_0_reg_683[22:7]}};
        trunc_ln708_106_reg_2889 <= {{acc_V_31_0_reg_671[22:7]}};
        trunc_ln708_77_reg_2744 <= {{acc_V_2_0_reg_1019[22:7]}};
        trunc_ln708_78_reg_2749 <= {{acc_V_3_0_reg_1007[22:7]}};
        trunc_ln708_79_reg_2754 <= {{acc_V_4_0_reg_995[22:7]}};
        trunc_ln708_80_reg_2759 <= {{acc_V_5_0_reg_983[22:7]}};
        trunc_ln708_81_reg_2764 <= {{acc_V_6_0_reg_971[22:7]}};
        trunc_ln708_82_reg_2769 <= {{acc_V_7_0_reg_959[22:7]}};
        trunc_ln708_83_reg_2774 <= {{acc_V_8_0_reg_947[22:7]}};
        trunc_ln708_84_reg_2779 <= {{acc_V_9_0_reg_935[22:7]}};
        trunc_ln708_85_reg_2784 <= {{acc_V_10_0_reg_923[22:7]}};
        trunc_ln708_86_reg_2789 <= {{acc_V_11_0_reg_911[22:7]}};
        trunc_ln708_87_reg_2794 <= {{acc_V_12_0_reg_899[22:7]}};
        trunc_ln708_88_reg_2799 <= {{acc_V_13_0_reg_887[22:7]}};
        trunc_ln708_89_reg_2804 <= {{acc_V_14_0_reg_875[22:7]}};
        trunc_ln708_90_reg_2809 <= {{acc_V_15_0_reg_863[22:7]}};
        trunc_ln708_91_reg_2814 <= {{acc_V_16_0_reg_851[22:7]}};
        trunc_ln708_92_reg_2819 <= {{acc_V_17_0_reg_839[22:7]}};
        trunc_ln708_93_reg_2824 <= {{acc_V_18_0_reg_827[22:7]}};
        trunc_ln708_94_reg_2829 <= {{acc_V_19_0_reg_815[22:7]}};
        trunc_ln708_95_reg_2834 <= {{acc_V_20_0_reg_803[22:7]}};
        trunc_ln708_96_reg_2839 <= {{acc_V_21_0_reg_791[22:7]}};
        trunc_ln708_97_reg_2844 <= {{acc_V_22_0_reg_779[22:7]}};
        trunc_ln708_98_reg_2849 <= {{acc_V_23_0_reg_767[22:7]}};
        trunc_ln708_99_reg_2854 <= {{acc_V_24_0_reg_755[22:7]}};
    end
end

always @ (*) begin
    if ((icmp_ln324_fu_1204_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state5 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state5 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln313_fu_1097_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln315_fu_1109_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        data_V_V_blk_n = data_V_V_empty_n;
    end else begin
        data_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((icmp_ln315_fu_1109_p2 == 1'd0) & (data_V_V_empty_n == 1'b0)) & (icmp_ln315_fu_1109_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        data_V_V_read = 1'b1;
    end else begin
        data_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln313_fu_1097_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer_in_V_7_address0 = zext_ln332_fu_1216_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        layer_in_V_7_address0 = grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_output_V_address0;
    end else begin
        layer_in_V_7_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer_in_V_7_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        layer_in_V_7_ce0 = grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_output_V_ce0;
    end else begin
        layer_in_V_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        layer_in_V_7_we0 = grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_output_V_we0;
    end else begin
        layer_in_V_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        layer_out_i_address0 = zext_ln340_fu_2006_p1;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        layer_out_i_address0 = 64'd30;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        layer_out_i_address0 = 64'd28;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        layer_out_i_address0 = 64'd26;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        layer_out_i_address0 = 64'd24;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        layer_out_i_address0 = 64'd22;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        layer_out_i_address0 = 64'd20;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        layer_out_i_address0 = 64'd18;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        layer_out_i_address0 = 64'd16;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        layer_out_i_address0 = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        layer_out_i_address0 = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        layer_out_i_address0 = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        layer_out_i_address0 = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        layer_out_i_address0 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        layer_out_i_address0 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        layer_out_i_address0 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        layer_out_i_address0 = 64'd0;
    end else begin
        layer_out_i_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        layer_out_i_address1 = 64'd31;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        layer_out_i_address1 = 64'd29;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        layer_out_i_address1 = 64'd27;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        layer_out_i_address1 = 64'd25;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        layer_out_i_address1 = 64'd23;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        layer_out_i_address1 = 64'd21;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        layer_out_i_address1 = 64'd19;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        layer_out_i_address1 = 64'd17;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        layer_out_i_address1 = 64'd15;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        layer_out_i_address1 = 64'd13;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        layer_out_i_address1 = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        layer_out_i_address1 = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        layer_out_i_address1 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        layer_out_i_address1 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        layer_out_i_address1 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        layer_out_i_address1 = 64'd1;
    end else begin
        layer_out_i_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state7))) begin
        layer_out_i_ce0 = 1'b1;
    end else begin
        layer_out_i_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state7))) begin
        layer_out_i_ce1 = 1'b1;
    end else begin
        layer_out_i_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        layer_out_i_d0 = trunc_ln708_105_reg_2884;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        layer_out_i_d0 = trunc_ln708_103_reg_2874;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        layer_out_i_d0 = trunc_ln708_101_reg_2864;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        layer_out_i_d0 = trunc_ln708_99_reg_2854;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        layer_out_i_d0 = trunc_ln708_97_reg_2844;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        layer_out_i_d0 = trunc_ln708_95_reg_2834;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        layer_out_i_d0 = trunc_ln708_93_reg_2824;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        layer_out_i_d0 = trunc_ln708_91_reg_2814;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        layer_out_i_d0 = trunc_ln708_89_reg_2804;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        layer_out_i_d0 = trunc_ln708_87_reg_2794;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        layer_out_i_d0 = trunc_ln708_85_reg_2784;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        layer_out_i_d0 = trunc_ln708_83_reg_2774;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        layer_out_i_d0 = trunc_ln708_81_reg_2764;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        layer_out_i_d0 = trunc_ln708_79_reg_2754;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        layer_out_i_d0 = trunc_ln708_77_reg_2744;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        layer_out_i_d0 = {{acc_V_0_0_reg_1043[22:7]}};
    end else begin
        layer_out_i_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state22)) begin
        layer_out_i_d1 = trunc_ln708_106_reg_2889;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        layer_out_i_d1 = trunc_ln708_104_reg_2879;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        layer_out_i_d1 = trunc_ln708_102_reg_2869;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        layer_out_i_d1 = trunc_ln708_100_reg_2859;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        layer_out_i_d1 = trunc_ln708_98_reg_2849;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        layer_out_i_d1 = trunc_ln708_96_reg_2839;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        layer_out_i_d1 = trunc_ln708_94_reg_2829;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        layer_out_i_d1 = trunc_ln708_92_reg_2819;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        layer_out_i_d1 = trunc_ln708_90_reg_2809;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        layer_out_i_d1 = trunc_ln708_88_reg_2799;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        layer_out_i_d1 = trunc_ln708_86_reg_2789;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        layer_out_i_d1 = trunc_ln708_84_reg_2779;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        layer_out_i_d1 = trunc_ln708_82_reg_2769;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        layer_out_i_d1 = trunc_ln708_80_reg_2759;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        layer_out_i_d1 = trunc_ln708_78_reg_2749;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        layer_out_i_d1 = {{acc_V_1_0_reg_1031[22:7]}};
    end else begin
        layer_out_i_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state7))) begin
        layer_out_i_we0 = 1'b1;
    end else begin
        layer_out_i_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state7))) begin
        layer_out_i_we1 = 1'b1;
    end else begin
        layer_out_i_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state24)) begin
        res_V_V_blk_n = res_V_V_full_n;
    end else begin
        res_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state24))) begin
        res_V_V_write = 1'b1;
    end else begin
        res_V_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln315_fu_1109_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        tmpdata_V_address0 = zext_ln317_fu_1121_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        tmpdata_V_address0 = grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_data_V_address0;
    end else begin
        tmpdata_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((~((icmp_ln315_fu_1109_p2 == 1'd0) & (data_V_V_empty_n == 1'b0)) & (icmp_ln315_fu_1109_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        tmpdata_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        tmpdata_V_ce0 = grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_data_V_ce0;
    end else begin
        tmpdata_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((icmp_ln315_fu_1109_p2 == 1'd0) & (data_V_V_empty_n == 1'b0)) & (icmp_ln315_fu_1109_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        tmpdata_V_we0 = 1'b1;
    end else begin
        tmpdata_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w2_V_ce0 = 1'b1;
    end else begin
        w2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln313_fu_1097_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if ((~((icmp_ln315_fu_1109_p2 == 1'd0) & (data_V_V_empty_n == 1'b0)) & (icmp_ln315_fu_1109_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else if ((~((icmp_ln315_fu_1109_p2 == 1'd0) & (data_V_V_empty_n == 1'b0)) & (icmp_ln315_fu_1109_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'd1 == and_ln326_6_fu_1198_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'd0 == and_ln326_6_fu_1198_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln324_fu_1204_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln324_fu_1204_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            if (((1'b1 == ap_CS_fsm_state23) & ((1'd0 == and_ln326_6_reg_2561) | (icmp_ln338_fu_1994_p2 == 1'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end
        end
        ap_ST_fsm_state24 : begin
            if (((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state24))) begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln354_fu_2062_p2 = (pY_2_load_reg_2549 + 32'd1);

assign add_ln356_fu_2073_p2 = (sY_2_load_reg_2539 + 32'd1);

assign add_ln359_fu_2016_p2 = (pX_2_load_reg_2555 + 32'd1);

assign add_ln361_fu_2027_p2 = (sX_2_load_reg_2529 + 32'd1);

assign and_ln326_5_fu_1192_p2 = (icmp_ln326_9_fu_1180_p2 & icmp_ln326_8_fu_1160_p2);

assign and_ln326_6_fu_1198_p2 = (and_ln326_fu_1186_p2 & and_ln326_5_fu_1192_p2);

assign and_ln326_fu_1186_p2 = (icmp_ln326_fu_1130_p2 & icmp_ln326_7_fu_1140_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd7];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

always @ (*) begin
    ap_block_state3 = ((icmp_ln315_fu_1109_p2 == 1'd0) & (data_V_V_empty_n == 1'b0));
end

always @ (*) begin
    ap_block_state3_ignore_call0 = ((icmp_ln315_fu_1109_p2 == 1'd0) & (data_V_V_empty_n == 1'b0));
end

assign ap_block_state5_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_470 = (((icmp_ln350_fu_2057_p2 == 1'd0) & (1'd0 == and_ln326_6_reg_2561) & (icmp_ln346_fu_2011_p2 == 1'd1)) | ((icmp_ln350_fu_2057_p2 == 1'd0) & (icmp_ln346_fu_2011_p2 == 1'd1) & (icmp_ln338_fu_1994_p2 == 1'd1)));
end

always @ (*) begin
    ap_condition_592 = (((1'd0 == and_ln326_6_reg_2561) & (icmp_ln350_fu_2057_p2 == 1'd1) & (icmp_ln346_fu_2011_p2 == 1'd1)) | ((icmp_ln350_fu_2057_p2 == 1'd1) & (icmp_ln346_fu_2011_p2 == 1'd1) & (icmp_ln338_fu_1994_p2 == 1'd1)));
end

always @ (*) begin
    ap_condition_654 = (((icmp_ln346_fu_2011_p2 == 1'd0) & (1'd0 == and_ln326_6_reg_2561)) | ((icmp_ln346_fu_2011_p2 == 1'd0) & (icmp_ln338_fu_1994_p2 == 1'd1)));
end

always @ (*) begin
    ap_condition_656 = (((1'd0 == and_ln326_6_reg_2561) & (icmp_ln346_fu_2011_p2 == 1'd1)) | ((icmp_ln346_fu_2011_p2 == 1'd1) & (icmp_ln338_fu_1994_p2 == 1'd1)));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_ready = internal_ap_ready;

assign grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_start = grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config2_s_fu_1088_ap_start_reg;

assign grp_fu_2097_p1 = sext_ln1116_fu_1226_p1;

assign grp_fu_2105_p1 = sext_ln1116_fu_1226_p1;

assign grp_fu_2113_p1 = sext_ln1116_fu_1226_p1;

assign grp_fu_2121_p1 = sext_ln1116_fu_1226_p1;

assign grp_fu_2129_p1 = sext_ln1116_fu_1226_p1;

assign grp_fu_2137_p1 = sext_ln1116_fu_1226_p1;

assign grp_fu_2145_p1 = sext_ln1116_fu_1226_p1;

assign grp_fu_2153_p1 = sext_ln1116_fu_1226_p1;

assign grp_fu_2161_p1 = sext_ln1116_fu_1226_p1;

assign grp_fu_2169_p1 = sext_ln1116_fu_1226_p1;

assign grp_fu_2177_p1 = sext_ln1116_fu_1226_p1;

assign grp_fu_2185_p1 = sext_ln1116_fu_1226_p1;

assign grp_fu_2193_p1 = sext_ln1116_fu_1226_p1;

assign grp_fu_2201_p1 = sext_ln1116_fu_1226_p1;

assign grp_fu_2209_p1 = sext_ln1116_fu_1226_p1;

assign grp_fu_2217_p1 = sext_ln1116_fu_1226_p1;

assign grp_fu_2225_p1 = sext_ln1116_fu_1226_p1;

assign grp_fu_2233_p1 = sext_ln1116_fu_1226_p1;

assign grp_fu_2241_p1 = sext_ln1116_fu_1226_p1;

assign grp_fu_2249_p1 = sext_ln1116_fu_1226_p1;

assign grp_fu_2257_p1 = sext_ln1116_fu_1226_p1;

assign grp_fu_2265_p1 = sext_ln1116_fu_1226_p1;

assign grp_fu_2273_p1 = sext_ln1116_fu_1226_p1;

assign grp_fu_2281_p1 = sext_ln1116_fu_1226_p1;

assign grp_fu_2289_p1 = sext_ln1116_fu_1226_p1;

assign grp_fu_2297_p1 = sext_ln1116_fu_1226_p1;

assign grp_fu_2305_p1 = sext_ln1116_fu_1226_p1;

assign grp_fu_2313_p1 = sext_ln1116_fu_1226_p1;

assign grp_fu_2321_p1 = sext_ln1116_fu_1226_p1;

assign grp_fu_2329_p1 = sext_ln1116_fu_1226_p1;

assign grp_fu_2337_p1 = sext_ln1116_fu_1226_p1;

assign i1_fu_1115_p2 = (i1_0_i_reg_660 + 2'd1);

assign i_fu_1103_p2 = (i_0_i_reg_649 + 13'd1);

assign i_ic_fu_2000_p2 = (i_ic_0_i_reg_1066 + 6'd1);

assign icmp_ln313_fu_1097_p2 = ((i_0_i_reg_649 == 13'd4356) ? 1'b1 : 1'b0);

assign icmp_ln315_fu_1109_p2 = ((i1_0_i_reg_660 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln324_fu_1204_p2 = ((in_index_reg_1055 == 5'd27) ? 1'b1 : 1'b0);

assign icmp_ln326_7_fu_1140_p2 = ((sY_2 == 32'd2) ? 1'b1 : 1'b0);

assign icmp_ln326_8_fu_1160_p2 = (($signed(tmp_7_fu_1150_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln326_9_fu_1180_p2 = (($signed(tmp_8_fu_1170_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln326_fu_1130_p2 = ((sX_2 == 32'd2) ? 1'b1 : 1'b0);

assign icmp_ln338_fu_1994_p2 = ((i_ic_0_i_reg_1066 == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln346_fu_2011_p2 = ((pX_2_load_reg_2555 == 32'd65) ? 1'b1 : 1'b0);

assign icmp_ln350_fu_2057_p2 = ((pY_2_load_reg_2549 == 32'd65) ? 1'b1 : 1'b0);

assign ir_fu_1210_p2 = (in_index_reg_1055 + 5'd1);

assign res_V_V_din = layer_out_i_q0;

assign select_ln356_fu_2078_p3 = ((icmp_ln326_7_reg_2544[0:0] === 1'b1) ? 32'd2 : add_ln356_fu_2073_p2);

assign select_ln361_fu_2032_p3 = ((icmp_ln326_reg_2534[0:0] === 1'b1) ? 32'd2 : add_ln361_fu_2027_p2);

assign sext_ln1116_fu_1226_p0 = layer_in_V_7_q0;

assign sext_ln1116_fu_1226_p1 = sext_ln1116_fu_1226_p0;

assign start_out = real_start;

assign tmp_126_fu_1238_p4 = {{w2_V_q0[15:8]}};

assign tmp_127_fu_1252_p4 = {{w2_V_q0[23:16]}};

assign tmp_128_fu_1266_p4 = {{w2_V_q0[31:24]}};

assign tmp_129_fu_1280_p4 = {{w2_V_q0[39:32]}};

assign tmp_130_fu_1294_p4 = {{w2_V_q0[47:40]}};

assign tmp_131_fu_1308_p4 = {{w2_V_q0[55:48]}};

assign tmp_132_fu_1322_p4 = {{w2_V_q0[63:56]}};

assign tmp_133_fu_1336_p4 = {{w2_V_q0[71:64]}};

assign tmp_134_fu_1350_p4 = {{w2_V_q0[79:72]}};

assign tmp_135_fu_1364_p4 = {{w2_V_q0[87:80]}};

assign tmp_136_fu_1378_p4 = {{w2_V_q0[95:88]}};

assign tmp_137_fu_1392_p4 = {{w2_V_q0[103:96]}};

assign tmp_138_fu_1406_p4 = {{w2_V_q0[111:104]}};

assign tmp_139_fu_1420_p4 = {{w2_V_q0[119:112]}};

assign tmp_140_fu_1434_p4 = {{w2_V_q0[127:120]}};

assign tmp_141_fu_1448_p4 = {{w2_V_q0[135:128]}};

assign tmp_142_fu_1462_p4 = {{w2_V_q0[143:136]}};

assign tmp_143_fu_1476_p4 = {{w2_V_q0[151:144]}};

assign tmp_144_fu_1490_p4 = {{w2_V_q0[159:152]}};

assign tmp_145_fu_1504_p4 = {{w2_V_q0[167:160]}};

assign tmp_146_fu_1518_p4 = {{w2_V_q0[175:168]}};

assign tmp_147_fu_1532_p4 = {{w2_V_q0[183:176]}};

assign tmp_148_fu_1546_p4 = {{w2_V_q0[191:184]}};

assign tmp_149_fu_1560_p4 = {{w2_V_q0[199:192]}};

assign tmp_150_fu_1574_p4 = {{w2_V_q0[207:200]}};

assign tmp_151_fu_1588_p4 = {{w2_V_q0[215:208]}};

assign tmp_152_fu_1602_p4 = {{w2_V_q0[223:216]}};

assign tmp_153_fu_1616_p4 = {{w2_V_q0[231:224]}};

assign tmp_154_fu_1630_p4 = {{w2_V_q0[239:232]}};

assign tmp_155_fu_1644_p4 = {{w2_V_q0[247:240]}};

assign tmp_4_fu_1658_p4 = {{w2_V_q0[254:248]}};

assign tmp_7_fu_1150_p4 = {{pY_2[31:1]}};

assign tmp_8_fu_1170_p4 = {{pX_2[31:1]}};

assign trunc_ln332_fu_1222_p1 = w2_V_q0[7:0];

assign w2_V_address0 = zext_ln332_fu_1216_p1;

assign zext_ln317_fu_1121_p1 = i1_0_i_reg_660;

assign zext_ln332_fu_1216_p1 = in_index_reg_1055;

assign zext_ln340_fu_2006_p1 = i_ic_0_i_reg_1066;

endmodule //conv_2d_cl_ss_ap_fixed_ap_fixed_16_4_5_3_0_config2_s
