// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module conv_2d_cl_ss_ap_fixed_ap_fixed_16_4_5_3_0_config12_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        data_V_V_dout,
        data_V_V_empty_n,
        data_V_V_read,
        res_V_V_din,
        res_V_V_full_n,
        res_V_V_write
);

parameter    ap_ST_fsm_state1 = 32'd1;
parameter    ap_ST_fsm_state2 = 32'd2;
parameter    ap_ST_fsm_state3 = 32'd4;
parameter    ap_ST_fsm_state4 = 32'd8;
parameter    ap_ST_fsm_pp0_stage0 = 32'd16;
parameter    ap_ST_fsm_state7 = 32'd32;
parameter    ap_ST_fsm_state8 = 32'd64;
parameter    ap_ST_fsm_state9 = 32'd128;
parameter    ap_ST_fsm_state10 = 32'd256;
parameter    ap_ST_fsm_state11 = 32'd512;
parameter    ap_ST_fsm_state12 = 32'd1024;
parameter    ap_ST_fsm_state13 = 32'd2048;
parameter    ap_ST_fsm_state14 = 32'd4096;
parameter    ap_ST_fsm_state15 = 32'd8192;
parameter    ap_ST_fsm_state16 = 32'd16384;
parameter    ap_ST_fsm_state17 = 32'd32768;
parameter    ap_ST_fsm_state18 = 32'd65536;
parameter    ap_ST_fsm_state19 = 32'd131072;
parameter    ap_ST_fsm_state20 = 32'd262144;
parameter    ap_ST_fsm_state21 = 32'd524288;
parameter    ap_ST_fsm_state22 = 32'd1048576;
parameter    ap_ST_fsm_state23 = 32'd2097152;
parameter    ap_ST_fsm_state24 = 32'd4194304;
parameter    ap_ST_fsm_state25 = 32'd8388608;
parameter    ap_ST_fsm_state26 = 32'd16777216;
parameter    ap_ST_fsm_state27 = 32'd33554432;
parameter    ap_ST_fsm_state28 = 32'd67108864;
parameter    ap_ST_fsm_state29 = 32'd134217728;
parameter    ap_ST_fsm_state30 = 32'd268435456;
parameter    ap_ST_fsm_state31 = 32'd536870912;
parameter    ap_ST_fsm_state32 = 32'd1073741824;
parameter    ap_ST_fsm_state33 = 32'd2147483648;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [15:0] data_V_V_dout;
input   data_V_V_empty_n;
output   data_V_V_read;
output  [15:0] res_V_V_din;
input   res_V_V_full_n;
output   res_V_V_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg data_V_V_read;
reg res_V_V_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [31:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg   [8:0] layer_in_V_address0;
reg    layer_in_V_ce0;
reg    layer_in_V_we0;
wire  signed [15:0] layer_in_V_q0;
reg   [31:0] sX_5;
reg   [31:0] sY_5;
reg   [31:0] pY_5;
reg   [31:0] pX_5;
wire   [8:0] w12_V_address0;
reg    w12_V_ce0;
wire   [380:0] w12_V_q0;
reg    data_V_V_blk_n;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln315_fu_1521_p2;
reg    res_V_V_blk_n;
wire    ap_CS_fsm_state32;
reg   [23:0] acc_V_47_0_reg_891;
reg   [23:0] acc_V_46_0_reg_903;
reg   [23:0] acc_V_45_0_reg_915;
reg   [23:0] acc_V_44_0_reg_927;
reg   [23:0] acc_V_43_0_reg_939;
reg   [23:0] acc_V_42_0_reg_951;
reg   [23:0] acc_V_41_0_reg_963;
reg   [23:0] acc_V_40_0_reg_975;
reg   [23:0] acc_V_39_0_reg_987;
reg   [23:0] acc_V_38_0_reg_999;
reg   [23:0] acc_V_37_0_reg_1011;
reg   [23:0] acc_V_36_0_reg_1023;
reg   [23:0] acc_V_35_0_reg_1035;
reg   [23:0] acc_V_34_0_reg_1047;
reg   [23:0] acc_V_33_0_reg_1059;
reg   [23:0] acc_V_32_0_reg_1071;
reg   [23:0] acc_V_31_0_reg_1083;
reg   [23:0] acc_V_30_0_reg_1095;
reg   [23:0] acc_V_29_0_reg_1107;
reg   [23:0] acc_V_28_0_reg_1119;
reg   [23:0] acc_V_27_0_reg_1131;
reg   [23:0] acc_V_26_0_reg_1143;
reg   [23:0] acc_V_25_0_reg_1155;
reg   [23:0] acc_V_24_0_reg_1167;
reg   [23:0] acc_V_23_0_reg_1179;
reg   [23:0] acc_V_22_0_reg_1191;
reg   [23:0] acc_V_21_0_reg_1203;
reg   [23:0] acc_V_20_0_reg_1215;
reg   [23:0] acc_V_19_0_reg_1227;
reg   [23:0] acc_V_18_0_reg_1239;
reg   [23:0] acc_V_17_0_reg_1251;
reg   [23:0] acc_V_16_0_reg_1263;
reg   [23:0] acc_V_15_0_reg_1275;
reg   [23:0] acc_V_14_0_reg_1287;
reg   [23:0] acc_V_13_0_reg_1299;
reg   [23:0] acc_V_12_0_reg_1311;
reg   [23:0] acc_V_11_0_reg_1323;
reg   [23:0] acc_V_10_0_reg_1335;
reg   [23:0] acc_V_9_0_reg_1347;
reg   [23:0] acc_V_8_0_reg_1359;
reg   [23:0] acc_V_7_0_reg_1371;
reg   [23:0] acc_V_6_0_reg_1383;
reg   [23:0] acc_V_5_0_reg_1395;
reg   [23:0] acc_V_4_0_reg_1407;
reg   [23:0] acc_V_3_0_reg_1419;
reg   [23:0] acc_V_2_0_reg_1431;
reg   [23:0] acc_V_1_0_reg_1443;
reg   [23:0] acc_V_0_0_reg_1455;
reg   [8:0] in_index_reg_1467;
reg    ap_block_state1;
wire   [10:0] i_fu_1515_p2;
reg   [10:0] i_reg_3520;
wire    ap_CS_fsm_state2;
wire   [5:0] i1_fu_1527_p2;
reg    ap_block_state3;
reg   [31:0] sX_5_load_reg_3533;
wire    ap_CS_fsm_state4;
wire    grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_ready;
wire    grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done;
wire   [0:0] icmp_ln326_fu_1542_p2;
reg   [0:0] icmp_ln326_reg_3538;
reg   [31:0] sY_5_load_reg_3543;
wire   [0:0] icmp_ln326_16_fu_1552_p2;
reg   [0:0] icmp_ln326_16_reg_3548;
reg   [31:0] pY_5_load_reg_3553;
reg   [31:0] pX_5_load_reg_3559;
wire   [0:0] and_ln326_12_fu_1610_p2;
reg   [0:0] and_ln326_12_reg_3565;
wire   [0:0] icmp_ln324_fu_1616_p2;
reg   [0:0] icmp_ln324_reg_3569;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state5_pp0_stage0_iter0;
wire    ap_block_state6_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire   [8:0] ir_fu_1622_p2;
reg    ap_enable_reg_pp0_iter0;
wire  signed [23:0] grp_fu_2893_p3;
reg    ap_enable_reg_pp0_iter1;
wire  signed [23:0] grp_fu_2901_p3;
wire  signed [23:0] grp_fu_2909_p3;
wire  signed [23:0] grp_fu_2917_p3;
wire  signed [23:0] grp_fu_2925_p3;
wire  signed [23:0] grp_fu_2933_p3;
wire  signed [23:0] grp_fu_2941_p3;
wire  signed [23:0] grp_fu_2949_p3;
wire  signed [23:0] grp_fu_2957_p3;
wire  signed [23:0] grp_fu_2965_p3;
wire  signed [23:0] grp_fu_2973_p3;
wire  signed [23:0] grp_fu_2981_p3;
wire  signed [23:0] grp_fu_2989_p3;
wire  signed [23:0] grp_fu_2997_p3;
wire  signed [23:0] grp_fu_3005_p3;
wire  signed [23:0] grp_fu_3013_p3;
wire  signed [23:0] grp_fu_3021_p3;
wire  signed [23:0] grp_fu_3029_p3;
wire  signed [23:0] grp_fu_3037_p3;
wire  signed [23:0] grp_fu_3045_p3;
wire  signed [23:0] grp_fu_3053_p3;
wire  signed [23:0] grp_fu_3061_p3;
wire  signed [23:0] grp_fu_3069_p3;
wire  signed [23:0] grp_fu_3077_p3;
wire  signed [23:0] grp_fu_3085_p3;
wire  signed [23:0] grp_fu_3093_p3;
wire  signed [23:0] grp_fu_3101_p3;
wire  signed [23:0] grp_fu_3109_p3;
wire  signed [23:0] grp_fu_3117_p3;
wire  signed [23:0] grp_fu_3125_p3;
wire  signed [23:0] grp_fu_3133_p3;
wire  signed [23:0] grp_fu_3141_p3;
wire  signed [23:0] grp_fu_3149_p3;
wire  signed [23:0] grp_fu_3157_p3;
wire  signed [23:0] grp_fu_3165_p3;
wire  signed [23:0] grp_fu_3173_p3;
wire  signed [23:0] grp_fu_3181_p3;
wire  signed [23:0] grp_fu_3189_p3;
wire  signed [23:0] grp_fu_3197_p3;
wire  signed [23:0] grp_fu_3205_p3;
wire  signed [23:0] grp_fu_3213_p3;
wire  signed [23:0] grp_fu_3221_p3;
wire  signed [23:0] grp_fu_3229_p3;
wire  signed [23:0] grp_fu_3237_p3;
wire  signed [23:0] grp_fu_3245_p3;
wire  signed [23:0] grp_fu_3253_p3;
wire  signed [23:0] grp_fu_3261_p3;
wire  signed [23:0] grp_fu_3269_p3;
reg   [15:0] trunc_ln708_231_reg_3828;
wire    ap_CS_fsm_state7;
reg   [15:0] trunc_ln708_232_reg_3833;
reg   [15:0] trunc_ln708_233_reg_3838;
reg   [15:0] trunc_ln708_234_reg_3843;
reg   [15:0] trunc_ln708_235_reg_3848;
reg   [15:0] trunc_ln708_236_reg_3853;
reg   [15:0] trunc_ln708_237_reg_3858;
reg   [15:0] trunc_ln708_238_reg_3863;
reg   [15:0] trunc_ln708_239_reg_3868;
reg   [15:0] trunc_ln708_240_reg_3873;
reg   [15:0] trunc_ln708_241_reg_3878;
reg   [15:0] trunc_ln708_242_reg_3883;
reg   [15:0] trunc_ln708_243_reg_3888;
reg   [15:0] trunc_ln708_244_reg_3893;
reg   [15:0] trunc_ln708_245_reg_3898;
reg   [15:0] trunc_ln708_246_reg_3903;
reg   [15:0] trunc_ln708_247_reg_3908;
reg   [15:0] trunc_ln708_248_reg_3913;
reg   [15:0] trunc_ln708_249_reg_3918;
reg   [15:0] trunc_ln708_250_reg_3923;
reg   [15:0] trunc_ln708_251_reg_3928;
reg   [15:0] trunc_ln708_252_reg_3933;
reg   [15:0] trunc_ln708_253_reg_3938;
reg   [15:0] trunc_ln708_254_reg_3943;
reg   [15:0] trunc_ln708_255_reg_3948;
reg   [15:0] trunc_ln708_256_reg_3953;
reg   [15:0] trunc_ln708_257_reg_3958;
reg   [15:0] trunc_ln708_258_reg_3963;
reg   [15:0] trunc_ln708_259_reg_3968;
reg   [15:0] trunc_ln708_260_reg_3973;
reg   [15:0] trunc_ln708_261_reg_3978;
reg   [15:0] trunc_ln708_262_reg_3983;
reg   [15:0] trunc_ln708_263_reg_3988;
reg   [15:0] trunc_ln708_264_reg_3993;
reg   [15:0] trunc_ln708_265_reg_3998;
reg   [15:0] trunc_ln708_266_reg_4003;
reg   [15:0] trunc_ln708_267_reg_4008;
reg   [15:0] trunc_ln708_268_reg_4013;
reg   [15:0] trunc_ln708_269_reg_4018;
reg   [15:0] trunc_ln708_270_reg_4023;
reg   [15:0] trunc_ln708_271_reg_4028;
reg   [15:0] trunc_ln708_272_reg_4033;
reg   [15:0] trunc_ln708_273_reg_4038;
reg   [15:0] trunc_ln708_274_reg_4043;
reg   [15:0] trunc_ln708_275_reg_4048;
reg   [15:0] trunc_ln708_276_reg_4053;
wire   [5:0] i_ic_fu_2796_p2;
reg   [5:0] i_ic_reg_4061;
wire    ap_CS_fsm_state31;
wire   [0:0] icmp_ln338_fu_2790_p2;
wire   [0:0] icmp_ln346_fu_2807_p2;
reg   [0:0] icmp_ln346_reg_4071;
wire   [31:0] select_ln356_fu_2874_p3;
wire   [0:0] icmp_ln350_fu_2853_p2;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state5;
reg   [5:0] tmpdata_V_address0;
reg    tmpdata_V_ce0;
reg    tmpdata_V_we0;
wire   [15:0] tmpdata_V_q0;
reg   [5:0] layer_out_i_address0;
reg    layer_out_i_ce0;
reg    layer_out_i_we0;
reg   [15:0] layer_out_i_d0;
wire   [15:0] layer_out_i_q0;
reg   [5:0] layer_out_i_address1;
reg    layer_out_i_ce1;
reg    layer_out_i_we1;
reg   [15:0] layer_out_i_d1;
wire    grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_start;
wire    grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_idle;
wire   [5:0] grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_data_V_address0;
wire    grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_data_V_ce0;
wire   [8:0] grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_output_V_address0;
wire    grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_output_V_ce0;
wire    grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_output_V_we0;
wire   [15:0] grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_output_V_d0;
reg   [10:0] i_0_i_reg_869;
wire    ap_CS_fsm_state33;
reg   [5:0] i1_0_i_reg_880;
wire   [0:0] icmp_ln313_fu_1509_p2;
wire    ap_block_pp0_stage0;
reg   [5:0] i_ic_0_i_reg_1478;
wire    ap_CS_fsm_state30;
reg   [31:0] storemerge_i_reg_1489;
reg    grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_start_reg;
reg    ap_block_state3_ignore_call0;
wire   [63:0] zext_ln317_fu_1533_p1;
wire   [63:0] zext_ln332_fu_1628_p1;
wire   [63:0] zext_ln340_fu_2802_p1;
wire   [31:0] select_ln361_fu_2828_p3;
wire   [31:0] add_ln354_fu_2858_p2;
wire   [31:0] add_ln359_fu_2812_p2;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state19;
wire    ap_CS_fsm_state20;
wire    ap_CS_fsm_state21;
wire    ap_CS_fsm_state22;
wire    ap_CS_fsm_state23;
wire    ap_CS_fsm_state24;
wire    ap_CS_fsm_state25;
wire    ap_CS_fsm_state26;
wire    ap_CS_fsm_state27;
wire    ap_CS_fsm_state28;
wire    ap_CS_fsm_state29;
wire   [30:0] tmp_13_fu_1562_p4;
wire   [30:0] tmp_14_fu_1582_p4;
wire   [0:0] icmp_ln326_17_fu_1572_p2;
wire   [0:0] icmp_ln326_18_fu_1592_p2;
wire   [0:0] and_ln326_11_fu_1604_p2;
wire   [0:0] and_ln326_fu_1598_p2;
wire  signed [15:0] sext_ln1116_fu_1638_p0;
wire  signed [7:0] trunc_ln332_fu_1634_p1;
wire  signed [7:0] tmp_283_fu_1650_p4;
wire  signed [7:0] tmp_284_fu_1664_p4;
wire  signed [7:0] tmp_285_fu_1678_p4;
wire  signed [7:0] tmp_286_fu_1692_p4;
wire  signed [7:0] tmp_287_fu_1706_p4;
wire  signed [7:0] tmp_288_fu_1720_p4;
wire  signed [7:0] tmp_289_fu_1734_p4;
wire  signed [7:0] tmp_290_fu_1748_p4;
wire  signed [7:0] tmp_291_fu_1762_p4;
wire  signed [7:0] tmp_292_fu_1776_p4;
wire  signed [7:0] tmp_293_fu_1790_p4;
wire  signed [7:0] tmp_294_fu_1804_p4;
wire  signed [7:0] tmp_295_fu_1818_p4;
wire  signed [7:0] tmp_296_fu_1832_p4;
wire  signed [7:0] tmp_297_fu_1846_p4;
wire  signed [7:0] tmp_298_fu_1860_p4;
wire  signed [7:0] tmp_299_fu_1874_p4;
wire  signed [7:0] tmp_300_fu_1888_p4;
wire  signed [7:0] tmp_301_fu_1902_p4;
wire  signed [7:0] tmp_302_fu_1916_p4;
wire  signed [7:0] tmp_303_fu_1930_p4;
wire  signed [7:0] tmp_304_fu_1944_p4;
wire  signed [7:0] tmp_305_fu_1958_p4;
wire  signed [7:0] tmp_306_fu_1972_p4;
wire  signed [7:0] tmp_307_fu_1986_p4;
wire  signed [7:0] tmp_308_fu_2000_p4;
wire  signed [7:0] tmp_309_fu_2014_p4;
wire  signed [7:0] tmp_310_fu_2028_p4;
wire  signed [7:0] tmp_311_fu_2042_p4;
wire  signed [7:0] tmp_312_fu_2056_p4;
wire  signed [7:0] tmp_313_fu_2070_p4;
wire  signed [7:0] tmp_314_fu_2084_p4;
wire  signed [7:0] tmp_315_fu_2098_p4;
wire  signed [7:0] tmp_316_fu_2112_p4;
wire  signed [7:0] tmp_317_fu_2126_p4;
wire  signed [7:0] tmp_318_fu_2140_p4;
wire  signed [7:0] tmp_319_fu_2154_p4;
wire  signed [7:0] tmp_320_fu_2168_p4;
wire  signed [7:0] tmp_321_fu_2182_p4;
wire  signed [7:0] tmp_322_fu_2196_p4;
wire  signed [7:0] tmp_323_fu_2210_p4;
wire  signed [7:0] tmp_324_fu_2224_p4;
wire  signed [7:0] tmp_325_fu_2238_p4;
wire  signed [7:0] tmp_326_fu_2252_p4;
wire  signed [7:0] tmp_327_fu_2266_p4;
wire  signed [7:0] tmp_328_fu_2280_p4;
wire  signed [4:0] tmp_7_fu_2294_p4;
wire   [31:0] add_ln361_fu_2823_p2;
wire   [31:0] add_ln356_fu_2869_p2;
wire  signed [15:0] grp_fu_2893_p1;
wire  signed [23:0] sext_ln1116_fu_1638_p1;
wire  signed [15:0] grp_fu_2901_p1;
wire  signed [15:0] grp_fu_2909_p1;
wire  signed [15:0] grp_fu_2917_p1;
wire  signed [15:0] grp_fu_2925_p1;
wire  signed [15:0] grp_fu_2933_p1;
wire  signed [15:0] grp_fu_2941_p1;
wire  signed [15:0] grp_fu_2949_p1;
wire  signed [15:0] grp_fu_2957_p1;
wire  signed [15:0] grp_fu_2965_p1;
wire  signed [15:0] grp_fu_2973_p1;
wire  signed [15:0] grp_fu_2981_p1;
wire  signed [15:0] grp_fu_2989_p1;
wire  signed [15:0] grp_fu_2997_p1;
wire  signed [15:0] grp_fu_3005_p1;
wire  signed [15:0] grp_fu_3013_p1;
wire  signed [15:0] grp_fu_3021_p1;
wire  signed [15:0] grp_fu_3029_p1;
wire  signed [15:0] grp_fu_3037_p1;
wire  signed [15:0] grp_fu_3045_p1;
wire  signed [15:0] grp_fu_3053_p1;
wire  signed [15:0] grp_fu_3061_p1;
wire  signed [15:0] grp_fu_3069_p1;
wire  signed [15:0] grp_fu_3077_p1;
wire  signed [15:0] grp_fu_3085_p1;
wire  signed [15:0] grp_fu_3093_p1;
wire  signed [15:0] grp_fu_3101_p1;
wire  signed [15:0] grp_fu_3109_p1;
wire  signed [15:0] grp_fu_3117_p1;
wire  signed [15:0] grp_fu_3125_p1;
wire  signed [15:0] grp_fu_3133_p1;
wire  signed [15:0] grp_fu_3141_p1;
wire  signed [15:0] grp_fu_3149_p1;
wire  signed [15:0] grp_fu_3157_p1;
wire  signed [15:0] grp_fu_3165_p1;
wire  signed [15:0] grp_fu_3173_p1;
wire  signed [15:0] grp_fu_3181_p1;
wire  signed [15:0] grp_fu_3189_p1;
wire  signed [15:0] grp_fu_3197_p1;
wire  signed [15:0] grp_fu_3205_p1;
wire  signed [15:0] grp_fu_3213_p1;
wire  signed [15:0] grp_fu_3221_p1;
wire  signed [15:0] grp_fu_3229_p1;
wire  signed [15:0] grp_fu_3237_p1;
wire  signed [15:0] grp_fu_3245_p1;
wire  signed [15:0] grp_fu_3253_p1;
wire  signed [15:0] grp_fu_3261_p1;
reg   [31:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_821;
reg    ap_condition_823;
reg    ap_condition_606;
reg    ap_condition_743;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 32'd1;
#0 sX_5 = 32'd0;
#0 sY_5 = 32'd0;
#0 pY_5 = 32'd0;
#0 pX_5 = 32'd0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_start_reg = 1'b0;
end

conv_2d_cl_ss_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_layvdy #(
    .DataWidth( 16 ),
    .AddressRange( 432 ),
    .AddressWidth( 9 ))
layer_in_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(layer_in_V_address0),
    .ce0(layer_in_V_ce0),
    .we0(layer_in_V_we0),
    .d0(grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_output_V_d0),
    .q0(layer_in_V_q0)
);

conv_2d_cl_ss_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_w12_V #(
    .DataWidth( 381 ),
    .AddressRange( 432 ),
    .AddressWidth( 9 ))
w12_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w12_V_address0),
    .ce0(w12_V_ce0),
    .q0(w12_V_q0)
);

conv_2d_cl_ss_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_tmpwdI #(
    .DataWidth( 16 ),
    .AddressRange( 48 ),
    .AddressWidth( 6 ))
tmpdata_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(tmpdata_V_address0),
    .ce0(tmpdata_V_ce0),
    .we0(tmpdata_V_we0),
    .d0(data_V_V_dout),
    .q0(tmpdata_V_q0)
);

conv_2d_cl_ss_ap_fixed_ap_fixed_16_4_5_3_0_config9_s_layesc4 #(
    .DataWidth( 16 ),
    .AddressRange( 48 ),
    .AddressWidth( 6 ))
layer_out_i_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(layer_out_i_address0),
    .ce0(layer_out_i_ce0),
    .we0(layer_out_i_we0),
    .d0(layer_out_i_d0),
    .q0(layer_out_i_q0),
    .address1(layer_out_i_address1),
    .ce1(layer_out_i_ce1),
    .we1(layer_out_i_we1),
    .d1(layer_out_i_d1)
);

cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_start),
    .ap_done(grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done),
    .ap_idle(grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_idle),
    .ap_ready(grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_ready),
    .data_V_address0(grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_data_V_address0),
    .data_V_ce0(grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_data_V_ce0),
    .data_V_q0(tmpdata_V_q0),
    .output_V_address0(grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_output_V_address0),
    .output_V_ce0(grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_output_V_ce0),
    .output_V_we0(grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_output_V_we0),
    .output_V_d0(grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_output_V_d0),
    .output_V_q0(layer_in_V_q0)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U164(
    .din0(trunc_ln332_fu_1634_p1),
    .din1(grp_fu_2893_p1),
    .din2(acc_V_0_0_reg_1455),
    .dout(grp_fu_2893_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U165(
    .din0(tmp_283_fu_1650_p4),
    .din1(grp_fu_2901_p1),
    .din2(acc_V_1_0_reg_1443),
    .dout(grp_fu_2901_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U166(
    .din0(tmp_284_fu_1664_p4),
    .din1(grp_fu_2909_p1),
    .din2(acc_V_2_0_reg_1431),
    .dout(grp_fu_2909_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U167(
    .din0(tmp_285_fu_1678_p4),
    .din1(grp_fu_2917_p1),
    .din2(acc_V_3_0_reg_1419),
    .dout(grp_fu_2917_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U168(
    .din0(tmp_286_fu_1692_p4),
    .din1(grp_fu_2925_p1),
    .din2(acc_V_4_0_reg_1407),
    .dout(grp_fu_2925_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U169(
    .din0(tmp_287_fu_1706_p4),
    .din1(grp_fu_2933_p1),
    .din2(acc_V_5_0_reg_1395),
    .dout(grp_fu_2933_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U170(
    .din0(tmp_288_fu_1720_p4),
    .din1(grp_fu_2941_p1),
    .din2(acc_V_6_0_reg_1383),
    .dout(grp_fu_2941_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U171(
    .din0(tmp_289_fu_1734_p4),
    .din1(grp_fu_2949_p1),
    .din2(acc_V_7_0_reg_1371),
    .dout(grp_fu_2949_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U172(
    .din0(tmp_290_fu_1748_p4),
    .din1(grp_fu_2957_p1),
    .din2(acc_V_8_0_reg_1359),
    .dout(grp_fu_2957_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U173(
    .din0(tmp_291_fu_1762_p4),
    .din1(grp_fu_2965_p1),
    .din2(acc_V_9_0_reg_1347),
    .dout(grp_fu_2965_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U174(
    .din0(tmp_292_fu_1776_p4),
    .din1(grp_fu_2973_p1),
    .din2(acc_V_10_0_reg_1335),
    .dout(grp_fu_2973_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U175(
    .din0(tmp_293_fu_1790_p4),
    .din1(grp_fu_2981_p1),
    .din2(acc_V_11_0_reg_1323),
    .dout(grp_fu_2981_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U176(
    .din0(tmp_294_fu_1804_p4),
    .din1(grp_fu_2989_p1),
    .din2(acc_V_12_0_reg_1311),
    .dout(grp_fu_2989_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U177(
    .din0(tmp_295_fu_1818_p4),
    .din1(grp_fu_2997_p1),
    .din2(acc_V_13_0_reg_1299),
    .dout(grp_fu_2997_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U178(
    .din0(tmp_296_fu_1832_p4),
    .din1(grp_fu_3005_p1),
    .din2(acc_V_14_0_reg_1287),
    .dout(grp_fu_3005_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U179(
    .din0(tmp_297_fu_1846_p4),
    .din1(grp_fu_3013_p1),
    .din2(acc_V_15_0_reg_1275),
    .dout(grp_fu_3013_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U180(
    .din0(tmp_298_fu_1860_p4),
    .din1(grp_fu_3021_p1),
    .din2(acc_V_16_0_reg_1263),
    .dout(grp_fu_3021_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U181(
    .din0(tmp_299_fu_1874_p4),
    .din1(grp_fu_3029_p1),
    .din2(acc_V_17_0_reg_1251),
    .dout(grp_fu_3029_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U182(
    .din0(tmp_300_fu_1888_p4),
    .din1(grp_fu_3037_p1),
    .din2(acc_V_18_0_reg_1239),
    .dout(grp_fu_3037_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U183(
    .din0(tmp_301_fu_1902_p4),
    .din1(grp_fu_3045_p1),
    .din2(acc_V_19_0_reg_1227),
    .dout(grp_fu_3045_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U184(
    .din0(tmp_302_fu_1916_p4),
    .din1(grp_fu_3053_p1),
    .din2(acc_V_20_0_reg_1215),
    .dout(grp_fu_3053_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U185(
    .din0(tmp_303_fu_1930_p4),
    .din1(grp_fu_3061_p1),
    .din2(acc_V_21_0_reg_1203),
    .dout(grp_fu_3061_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U186(
    .din0(tmp_304_fu_1944_p4),
    .din1(grp_fu_3069_p1),
    .din2(acc_V_22_0_reg_1191),
    .dout(grp_fu_3069_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U187(
    .din0(tmp_305_fu_1958_p4),
    .din1(grp_fu_3077_p1),
    .din2(acc_V_23_0_reg_1179),
    .dout(grp_fu_3077_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U188(
    .din0(tmp_306_fu_1972_p4),
    .din1(grp_fu_3085_p1),
    .din2(acc_V_24_0_reg_1167),
    .dout(grp_fu_3085_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U189(
    .din0(tmp_307_fu_1986_p4),
    .din1(grp_fu_3093_p1),
    .din2(acc_V_25_0_reg_1155),
    .dout(grp_fu_3093_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U190(
    .din0(tmp_308_fu_2000_p4),
    .din1(grp_fu_3101_p1),
    .din2(acc_V_26_0_reg_1143),
    .dout(grp_fu_3101_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U191(
    .din0(tmp_309_fu_2014_p4),
    .din1(grp_fu_3109_p1),
    .din2(acc_V_27_0_reg_1131),
    .dout(grp_fu_3109_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U192(
    .din0(tmp_310_fu_2028_p4),
    .din1(grp_fu_3117_p1),
    .din2(acc_V_28_0_reg_1119),
    .dout(grp_fu_3117_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U193(
    .din0(tmp_311_fu_2042_p4),
    .din1(grp_fu_3125_p1),
    .din2(acc_V_29_0_reg_1107),
    .dout(grp_fu_3125_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U194(
    .din0(tmp_312_fu_2056_p4),
    .din1(grp_fu_3133_p1),
    .din2(acc_V_30_0_reg_1095),
    .dout(grp_fu_3133_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U195(
    .din0(tmp_313_fu_2070_p4),
    .din1(grp_fu_3141_p1),
    .din2(acc_V_31_0_reg_1083),
    .dout(grp_fu_3141_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U196(
    .din0(tmp_314_fu_2084_p4),
    .din1(grp_fu_3149_p1),
    .din2(acc_V_32_0_reg_1071),
    .dout(grp_fu_3149_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U197(
    .din0(tmp_315_fu_2098_p4),
    .din1(grp_fu_3157_p1),
    .din2(acc_V_33_0_reg_1059),
    .dout(grp_fu_3157_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U198(
    .din0(tmp_316_fu_2112_p4),
    .din1(grp_fu_3165_p1),
    .din2(acc_V_34_0_reg_1047),
    .dout(grp_fu_3165_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U199(
    .din0(tmp_317_fu_2126_p4),
    .din1(grp_fu_3173_p1),
    .din2(acc_V_35_0_reg_1035),
    .dout(grp_fu_3173_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U200(
    .din0(tmp_318_fu_2140_p4),
    .din1(grp_fu_3181_p1),
    .din2(acc_V_36_0_reg_1023),
    .dout(grp_fu_3181_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U201(
    .din0(tmp_319_fu_2154_p4),
    .din1(grp_fu_3189_p1),
    .din2(acc_V_37_0_reg_1011),
    .dout(grp_fu_3189_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U202(
    .din0(tmp_320_fu_2168_p4),
    .din1(grp_fu_3197_p1),
    .din2(acc_V_38_0_reg_999),
    .dout(grp_fu_3197_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U203(
    .din0(tmp_321_fu_2182_p4),
    .din1(grp_fu_3205_p1),
    .din2(acc_V_39_0_reg_987),
    .dout(grp_fu_3205_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U204(
    .din0(tmp_322_fu_2196_p4),
    .din1(grp_fu_3213_p1),
    .din2(acc_V_40_0_reg_975),
    .dout(grp_fu_3213_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U205(
    .din0(tmp_323_fu_2210_p4),
    .din1(grp_fu_3221_p1),
    .din2(acc_V_41_0_reg_963),
    .dout(grp_fu_3221_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U206(
    .din0(tmp_324_fu_2224_p4),
    .din1(grp_fu_3229_p1),
    .din2(acc_V_42_0_reg_951),
    .dout(grp_fu_3229_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U207(
    .din0(tmp_325_fu_2238_p4),
    .din1(grp_fu_3237_p1),
    .din2(acc_V_43_0_reg_939),
    .dout(grp_fu_3237_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U208(
    .din0(tmp_326_fu_2252_p4),
    .din1(grp_fu_3245_p1),
    .din2(acc_V_44_0_reg_927),
    .dout(grp_fu_3245_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U209(
    .din0(tmp_327_fu_2266_p4),
    .din1(grp_fu_3253_p1),
    .din2(acc_V_45_0_reg_915),
    .dout(grp_fu_3253_p3)
);

myproject_mac_muladd_8s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_8s_16s_24ns_24_1_1_U210(
    .din0(tmp_328_fu_2280_p4),
    .din1(grp_fu_3261_p1),
    .din2(acc_V_46_0_reg_903),
    .dout(grp_fu_3261_p3)
);

myproject_mac_muladd_5s_16s_24ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 24 ),
    .dout_WIDTH( 24 ))
myproject_mac_muladd_5s_16s_24ns_24_1_1_U211(
    .din0(tmp_7_fu_2294_p4),
    .din1(layer_in_V_q0),
    .din2(acc_V_47_0_reg_891),
    .dout(grp_fu_3269_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln313_fu_1509_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state5) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'd1 == and_ln326_12_fu_1610_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state5))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state5);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((1'd1 == and_ln326_12_fu_1610_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_start_reg <= 1'b0;
    end else begin
        if ((~((data_V_V_empty_n == 1'b0) & (icmp_ln315_fu_1521_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln315_fu_1521_p2 == 1'd1))) begin
            grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_start_reg <= 1'b1;
        end else if ((grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_ready == 1'b1)) begin
            grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln324_reg_3569 == 1'd0))) begin
        acc_V_0_0_reg_1455 <= grp_fu_2893_p3;
    end else if (((1'd1 == and_ln326_12_fu_1610_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_0_0_reg_1455 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln324_reg_3569 == 1'd0))) begin
        acc_V_10_0_reg_1335 <= grp_fu_2973_p3;
    end else if (((1'd1 == and_ln326_12_fu_1610_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_10_0_reg_1335 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln324_reg_3569 == 1'd0))) begin
        acc_V_11_0_reg_1323 <= grp_fu_2981_p3;
    end else if (((1'd1 == and_ln326_12_fu_1610_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_11_0_reg_1323 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln324_reg_3569 == 1'd0))) begin
        acc_V_12_0_reg_1311 <= grp_fu_2989_p3;
    end else if (((1'd1 == and_ln326_12_fu_1610_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_12_0_reg_1311 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln324_reg_3569 == 1'd0))) begin
        acc_V_13_0_reg_1299 <= grp_fu_2997_p3;
    end else if (((1'd1 == and_ln326_12_fu_1610_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_13_0_reg_1299 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln324_reg_3569 == 1'd0))) begin
        acc_V_14_0_reg_1287 <= grp_fu_3005_p3;
    end else if (((1'd1 == and_ln326_12_fu_1610_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_14_0_reg_1287 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln324_reg_3569 == 1'd0))) begin
        acc_V_15_0_reg_1275 <= grp_fu_3013_p3;
    end else if (((1'd1 == and_ln326_12_fu_1610_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_15_0_reg_1275 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln324_reg_3569 == 1'd0))) begin
        acc_V_16_0_reg_1263 <= grp_fu_3021_p3;
    end else if (((1'd1 == and_ln326_12_fu_1610_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_16_0_reg_1263 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln324_reg_3569 == 1'd0))) begin
        acc_V_17_0_reg_1251 <= grp_fu_3029_p3;
    end else if (((1'd1 == and_ln326_12_fu_1610_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_17_0_reg_1251 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln324_reg_3569 == 1'd0))) begin
        acc_V_18_0_reg_1239 <= grp_fu_3037_p3;
    end else if (((1'd1 == and_ln326_12_fu_1610_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_18_0_reg_1239 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln324_reg_3569 == 1'd0))) begin
        acc_V_19_0_reg_1227 <= grp_fu_3045_p3;
    end else if (((1'd1 == and_ln326_12_fu_1610_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_19_0_reg_1227 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln324_reg_3569 == 1'd0))) begin
        acc_V_1_0_reg_1443 <= grp_fu_2901_p3;
    end else if (((1'd1 == and_ln326_12_fu_1610_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_1_0_reg_1443 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln324_reg_3569 == 1'd0))) begin
        acc_V_20_0_reg_1215 <= grp_fu_3053_p3;
    end else if (((1'd1 == and_ln326_12_fu_1610_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_20_0_reg_1215 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln324_reg_3569 == 1'd0))) begin
        acc_V_21_0_reg_1203 <= grp_fu_3061_p3;
    end else if (((1'd1 == and_ln326_12_fu_1610_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_21_0_reg_1203 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln324_reg_3569 == 1'd0))) begin
        acc_V_22_0_reg_1191 <= grp_fu_3069_p3;
    end else if (((1'd1 == and_ln326_12_fu_1610_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_22_0_reg_1191 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln324_reg_3569 == 1'd0))) begin
        acc_V_23_0_reg_1179 <= grp_fu_3077_p3;
    end else if (((1'd1 == and_ln326_12_fu_1610_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_23_0_reg_1179 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln324_reg_3569 == 1'd0))) begin
        acc_V_24_0_reg_1167 <= grp_fu_3085_p3;
    end else if (((1'd1 == and_ln326_12_fu_1610_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_24_0_reg_1167 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln324_reg_3569 == 1'd0))) begin
        acc_V_25_0_reg_1155 <= grp_fu_3093_p3;
    end else if (((1'd1 == and_ln326_12_fu_1610_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_25_0_reg_1155 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln324_reg_3569 == 1'd0))) begin
        acc_V_26_0_reg_1143 <= grp_fu_3101_p3;
    end else if (((1'd1 == and_ln326_12_fu_1610_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_26_0_reg_1143 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln324_reg_3569 == 1'd0))) begin
        acc_V_27_0_reg_1131 <= grp_fu_3109_p3;
    end else if (((1'd1 == and_ln326_12_fu_1610_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_27_0_reg_1131 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln324_reg_3569 == 1'd0))) begin
        acc_V_28_0_reg_1119 <= grp_fu_3117_p3;
    end else if (((1'd1 == and_ln326_12_fu_1610_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_28_0_reg_1119 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln324_reg_3569 == 1'd0))) begin
        acc_V_29_0_reg_1107 <= grp_fu_3125_p3;
    end else if (((1'd1 == and_ln326_12_fu_1610_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_29_0_reg_1107 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln324_reg_3569 == 1'd0))) begin
        acc_V_2_0_reg_1431 <= grp_fu_2909_p3;
    end else if (((1'd1 == and_ln326_12_fu_1610_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_2_0_reg_1431 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln324_reg_3569 == 1'd0))) begin
        acc_V_30_0_reg_1095 <= grp_fu_3133_p3;
    end else if (((1'd1 == and_ln326_12_fu_1610_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_30_0_reg_1095 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln324_reg_3569 == 1'd0))) begin
        acc_V_31_0_reg_1083 <= grp_fu_3141_p3;
    end else if (((1'd1 == and_ln326_12_fu_1610_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_31_0_reg_1083 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln324_reg_3569 == 1'd0))) begin
        acc_V_32_0_reg_1071 <= grp_fu_3149_p3;
    end else if (((1'd1 == and_ln326_12_fu_1610_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_32_0_reg_1071 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln324_reg_3569 == 1'd0))) begin
        acc_V_33_0_reg_1059 <= grp_fu_3157_p3;
    end else if (((1'd1 == and_ln326_12_fu_1610_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_33_0_reg_1059 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln324_reg_3569 == 1'd0))) begin
        acc_V_34_0_reg_1047 <= grp_fu_3165_p3;
    end else if (((1'd1 == and_ln326_12_fu_1610_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_34_0_reg_1047 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln324_reg_3569 == 1'd0))) begin
        acc_V_35_0_reg_1035 <= grp_fu_3173_p3;
    end else if (((1'd1 == and_ln326_12_fu_1610_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_35_0_reg_1035 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln324_reg_3569 == 1'd0))) begin
        acc_V_36_0_reg_1023 <= grp_fu_3181_p3;
    end else if (((1'd1 == and_ln326_12_fu_1610_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_36_0_reg_1023 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln324_reg_3569 == 1'd0))) begin
        acc_V_37_0_reg_1011 <= grp_fu_3189_p3;
    end else if (((1'd1 == and_ln326_12_fu_1610_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_37_0_reg_1011 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln324_reg_3569 == 1'd0))) begin
        acc_V_38_0_reg_999 <= grp_fu_3197_p3;
    end else if (((1'd1 == and_ln326_12_fu_1610_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_38_0_reg_999 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln324_reg_3569 == 1'd0))) begin
        acc_V_39_0_reg_987 <= grp_fu_3205_p3;
    end else if (((1'd1 == and_ln326_12_fu_1610_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_39_0_reg_987 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln324_reg_3569 == 1'd0))) begin
        acc_V_3_0_reg_1419 <= grp_fu_2917_p3;
    end else if (((1'd1 == and_ln326_12_fu_1610_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_3_0_reg_1419 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln324_reg_3569 == 1'd0))) begin
        acc_V_40_0_reg_975 <= grp_fu_3213_p3;
    end else if (((1'd1 == and_ln326_12_fu_1610_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_40_0_reg_975 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln324_reg_3569 == 1'd0))) begin
        acc_V_41_0_reg_963 <= grp_fu_3221_p3;
    end else if (((1'd1 == and_ln326_12_fu_1610_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_41_0_reg_963 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln324_reg_3569 == 1'd0))) begin
        acc_V_42_0_reg_951 <= grp_fu_3229_p3;
    end else if (((1'd1 == and_ln326_12_fu_1610_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_42_0_reg_951 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln324_reg_3569 == 1'd0))) begin
        acc_V_43_0_reg_939 <= grp_fu_3237_p3;
    end else if (((1'd1 == and_ln326_12_fu_1610_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_43_0_reg_939 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln324_reg_3569 == 1'd0))) begin
        acc_V_44_0_reg_927 <= grp_fu_3245_p3;
    end else if (((1'd1 == and_ln326_12_fu_1610_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_44_0_reg_927 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln324_reg_3569 == 1'd0))) begin
        acc_V_45_0_reg_915 <= grp_fu_3253_p3;
    end else if (((1'd1 == and_ln326_12_fu_1610_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_45_0_reg_915 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln324_reg_3569 == 1'd0))) begin
        acc_V_46_0_reg_903 <= grp_fu_3261_p3;
    end else if (((1'd1 == and_ln326_12_fu_1610_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_46_0_reg_903 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln324_reg_3569 == 1'd0))) begin
        acc_V_47_0_reg_891 <= grp_fu_3269_p3;
    end else if (((1'd1 == and_ln326_12_fu_1610_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_47_0_reg_891 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln324_reg_3569 == 1'd0))) begin
        acc_V_4_0_reg_1407 <= grp_fu_2925_p3;
    end else if (((1'd1 == and_ln326_12_fu_1610_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_4_0_reg_1407 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln324_reg_3569 == 1'd0))) begin
        acc_V_5_0_reg_1395 <= grp_fu_2933_p3;
    end else if (((1'd1 == and_ln326_12_fu_1610_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_5_0_reg_1395 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln324_reg_3569 == 1'd0))) begin
        acc_V_6_0_reg_1383 <= grp_fu_2941_p3;
    end else if (((1'd1 == and_ln326_12_fu_1610_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_6_0_reg_1383 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln324_reg_3569 == 1'd0))) begin
        acc_V_7_0_reg_1371 <= grp_fu_2949_p3;
    end else if (((1'd1 == and_ln326_12_fu_1610_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_7_0_reg_1371 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln324_reg_3569 == 1'd0))) begin
        acc_V_8_0_reg_1359 <= grp_fu_2957_p3;
    end else if (((1'd1 == and_ln326_12_fu_1610_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_8_0_reg_1359 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln324_reg_3569 == 1'd0))) begin
        acc_V_9_0_reg_1347 <= grp_fu_2965_p3;
    end else if (((1'd1 == and_ln326_12_fu_1610_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_V_9_0_reg_1347 <= 24'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((data_V_V_empty_n == 1'b0) & (icmp_ln315_fu_1521_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln315_fu_1521_p2 == 1'd0))) begin
        i1_0_i_reg_880 <= i1_fu_1527_p2;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln313_fu_1509_p2 == 1'd0))) begin
        i1_0_i_reg_880 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state33)) begin
        i_0_i_reg_869 <= i_reg_3520;
    end else if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_0_i_reg_869 <= 11'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state32))) begin
        i_ic_0_i_reg_1478 <= i_ic_reg_4061;
    end else if ((1'b1 == ap_CS_fsm_state30)) begin
        i_ic_0_i_reg_1478 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln324_fu_1616_p2 == 1'd0))) begin
        in_index_reg_1467 <= ir_fu_1622_p2;
    end else if (((1'd1 == and_ln326_12_fu_1610_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        in_index_reg_1467 <= 9'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state31)) begin
        if ((1'b1 == ap_condition_823)) begin
            pX_5 <= 32'd0;
        end else if ((1'b1 == ap_condition_821)) begin
            pX_5 <= add_ln359_fu_2812_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state31)) begin
        if ((1'b1 == ap_condition_743)) begin
            pY_5 <= 32'd0;
        end else if ((1'b1 == ap_condition_606)) begin
            pY_5 <= add_ln354_fu_2858_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state31)) begin
        if ((1'b1 == ap_condition_823)) begin
            sX_5 <= 32'd0;
        end else if ((1'b1 == ap_condition_821)) begin
            sX_5 <= select_ln361_fu_2828_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state31)) begin
        if ((1'b1 == ap_condition_743)) begin
            storemerge_i_reg_1489 <= 32'd0;
        end else if ((1'b1 == ap_condition_606)) begin
            storemerge_i_reg_1489 <= select_ln356_fu_2874_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        and_ln326_12_reg_3565 <= and_ln326_12_fu_1610_p2;
        icmp_ln326_16_reg_3548 <= icmp_ln326_16_fu_1552_p2;
        icmp_ln326_reg_3538 <= icmp_ln326_fu_1542_p2;
        pX_5_load_reg_3559 <= pX_5;
        pY_5_load_reg_3553 <= pY_5;
        sX_5_load_reg_3533 <= sX_5;
        sY_5_load_reg_3543 <= sY_5;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd1 == and_ln326_12_reg_3565) & (1'b1 == ap_CS_fsm_state31))) begin
        i_ic_reg_4061 <= i_ic_fu_2796_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_reg_3520 <= i_fu_1515_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln324_reg_3569 <= icmp_ln324_fu_1616_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state31) & ((icmp_ln338_fu_2790_p2 == 1'd1) | (1'd0 == and_ln326_12_reg_3565)))) begin
        icmp_ln346_reg_4071 <= icmp_ln346_fu_2807_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln346_reg_4071 == 1'd1) & (1'b1 == ap_CS_fsm_state33))) begin
        sY_5 <= storemerge_i_reg_1489;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        trunc_ln708_231_reg_3828 <= {{acc_V_2_0_reg_1431[22:7]}};
        trunc_ln708_232_reg_3833 <= {{acc_V_3_0_reg_1419[22:7]}};
        trunc_ln708_233_reg_3838 <= {{acc_V_4_0_reg_1407[22:7]}};
        trunc_ln708_234_reg_3843 <= {{acc_V_5_0_reg_1395[22:7]}};
        trunc_ln708_235_reg_3848 <= {{acc_V_6_0_reg_1383[22:7]}};
        trunc_ln708_236_reg_3853 <= {{acc_V_7_0_reg_1371[22:7]}};
        trunc_ln708_237_reg_3858 <= {{acc_V_8_0_reg_1359[22:7]}};
        trunc_ln708_238_reg_3863 <= {{acc_V_9_0_reg_1347[22:7]}};
        trunc_ln708_239_reg_3868 <= {{acc_V_10_0_reg_1335[22:7]}};
        trunc_ln708_240_reg_3873 <= {{acc_V_11_0_reg_1323[22:7]}};
        trunc_ln708_241_reg_3878 <= {{acc_V_12_0_reg_1311[22:7]}};
        trunc_ln708_242_reg_3883 <= {{acc_V_13_0_reg_1299[22:7]}};
        trunc_ln708_243_reg_3888 <= {{acc_V_14_0_reg_1287[22:7]}};
        trunc_ln708_244_reg_3893 <= {{acc_V_15_0_reg_1275[22:7]}};
        trunc_ln708_245_reg_3898 <= {{acc_V_16_0_reg_1263[22:7]}};
        trunc_ln708_246_reg_3903 <= {{acc_V_17_0_reg_1251[22:7]}};
        trunc_ln708_247_reg_3908 <= {{acc_V_18_0_reg_1239[22:7]}};
        trunc_ln708_248_reg_3913 <= {{acc_V_19_0_reg_1227[22:7]}};
        trunc_ln708_249_reg_3918 <= {{acc_V_20_0_reg_1215[22:7]}};
        trunc_ln708_250_reg_3923 <= {{acc_V_21_0_reg_1203[22:7]}};
        trunc_ln708_251_reg_3928 <= {{acc_V_22_0_reg_1191[22:7]}};
        trunc_ln708_252_reg_3933 <= {{acc_V_23_0_reg_1179[22:7]}};
        trunc_ln708_253_reg_3938 <= {{acc_V_24_0_reg_1167[22:7]}};
        trunc_ln708_254_reg_3943 <= {{acc_V_25_0_reg_1155[22:7]}};
        trunc_ln708_255_reg_3948 <= {{acc_V_26_0_reg_1143[22:7]}};
        trunc_ln708_256_reg_3953 <= {{acc_V_27_0_reg_1131[22:7]}};
        trunc_ln708_257_reg_3958 <= {{acc_V_28_0_reg_1119[22:7]}};
        trunc_ln708_258_reg_3963 <= {{acc_V_29_0_reg_1107[22:7]}};
        trunc_ln708_259_reg_3968 <= {{acc_V_30_0_reg_1095[22:7]}};
        trunc_ln708_260_reg_3973 <= {{acc_V_31_0_reg_1083[22:7]}};
        trunc_ln708_261_reg_3978 <= {{acc_V_32_0_reg_1071[22:7]}};
        trunc_ln708_262_reg_3983 <= {{acc_V_33_0_reg_1059[22:7]}};
        trunc_ln708_263_reg_3988 <= {{acc_V_34_0_reg_1047[22:7]}};
        trunc_ln708_264_reg_3993 <= {{acc_V_35_0_reg_1035[22:7]}};
        trunc_ln708_265_reg_3998 <= {{acc_V_36_0_reg_1023[22:7]}};
        trunc_ln708_266_reg_4003 <= {{acc_V_37_0_reg_1011[22:7]}};
        trunc_ln708_267_reg_4008 <= {{acc_V_38_0_reg_999[22:7]}};
        trunc_ln708_268_reg_4013 <= {{acc_V_39_0_reg_987[22:7]}};
        trunc_ln708_269_reg_4018 <= {{acc_V_40_0_reg_975[22:7]}};
        trunc_ln708_270_reg_4023 <= {{acc_V_41_0_reg_963[22:7]}};
        trunc_ln708_271_reg_4028 <= {{acc_V_42_0_reg_951[22:7]}};
        trunc_ln708_272_reg_4033 <= {{acc_V_43_0_reg_939[22:7]}};
        trunc_ln708_273_reg_4038 <= {{acc_V_44_0_reg_927[22:7]}};
        trunc_ln708_274_reg_4043 <= {{acc_V_45_0_reg_915[22:7]}};
        trunc_ln708_275_reg_4048 <= {{acc_V_46_0_reg_903[22:7]}};
        trunc_ln708_276_reg_4053 <= {{acc_V_47_0_reg_891[22:7]}};
    end
end

always @ (*) begin
    if ((icmp_ln324_fu_1616_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state5 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state5 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln313_fu_1509_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln315_fu_1521_p2 == 1'd0))) begin
        data_V_V_blk_n = data_V_V_empty_n;
    end else begin
        data_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((data_V_V_empty_n == 1'b0) & (icmp_ln315_fu_1521_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln315_fu_1521_p2 == 1'd0))) begin
        data_V_V_read = 1'b1;
    end else begin
        data_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln313_fu_1509_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer_in_V_address0 = zext_ln332_fu_1628_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        layer_in_V_address0 = grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_output_V_address0;
    end else begin
        layer_in_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        layer_in_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        layer_in_V_ce0 = grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_output_V_ce0;
    end else begin
        layer_in_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        layer_in_V_we0 = grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_output_V_we0;
    end else begin
        layer_in_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state31)) begin
        layer_out_i_address0 = zext_ln340_fu_2802_p1;
    end else if ((1'b1 == ap_CS_fsm_state30)) begin
        layer_out_i_address0 = 64'd46;
    end else if ((1'b1 == ap_CS_fsm_state29)) begin
        layer_out_i_address0 = 64'd44;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        layer_out_i_address0 = 64'd42;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        layer_out_i_address0 = 64'd40;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        layer_out_i_address0 = 64'd38;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        layer_out_i_address0 = 64'd36;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        layer_out_i_address0 = 64'd34;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        layer_out_i_address0 = 64'd32;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        layer_out_i_address0 = 64'd30;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        layer_out_i_address0 = 64'd28;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        layer_out_i_address0 = 64'd26;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        layer_out_i_address0 = 64'd24;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        layer_out_i_address0 = 64'd22;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        layer_out_i_address0 = 64'd20;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        layer_out_i_address0 = 64'd18;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        layer_out_i_address0 = 64'd16;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        layer_out_i_address0 = 64'd14;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        layer_out_i_address0 = 64'd12;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        layer_out_i_address0 = 64'd10;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        layer_out_i_address0 = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        layer_out_i_address0 = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        layer_out_i_address0 = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        layer_out_i_address0 = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        layer_out_i_address0 = 64'd0;
    end else begin
        layer_out_i_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        layer_out_i_address1 = 64'd47;
    end else if ((1'b1 == ap_CS_fsm_state29)) begin
        layer_out_i_address1 = 64'd45;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        layer_out_i_address1 = 64'd43;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        layer_out_i_address1 = 64'd41;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        layer_out_i_address1 = 64'd39;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        layer_out_i_address1 = 64'd37;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        layer_out_i_address1 = 64'd35;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        layer_out_i_address1 = 64'd33;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        layer_out_i_address1 = 64'd31;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        layer_out_i_address1 = 64'd29;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        layer_out_i_address1 = 64'd27;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        layer_out_i_address1 = 64'd25;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        layer_out_i_address1 = 64'd23;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        layer_out_i_address1 = 64'd21;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        layer_out_i_address1 = 64'd19;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        layer_out_i_address1 = 64'd17;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        layer_out_i_address1 = 64'd15;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        layer_out_i_address1 = 64'd13;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        layer_out_i_address1 = 64'd11;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        layer_out_i_address1 = 64'd9;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        layer_out_i_address1 = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        layer_out_i_address1 = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        layer_out_i_address1 = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        layer_out_i_address1 = 64'd1;
    end else begin
        layer_out_i_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state7))) begin
        layer_out_i_ce0 = 1'b1;
    end else begin
        layer_out_i_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state7))) begin
        layer_out_i_ce1 = 1'b1;
    end else begin
        layer_out_i_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        layer_out_i_d0 = trunc_ln708_275_reg_4048;
    end else if ((1'b1 == ap_CS_fsm_state29)) begin
        layer_out_i_d0 = trunc_ln708_273_reg_4038;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        layer_out_i_d0 = trunc_ln708_271_reg_4028;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        layer_out_i_d0 = trunc_ln708_269_reg_4018;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        layer_out_i_d0 = trunc_ln708_267_reg_4008;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        layer_out_i_d0 = trunc_ln708_265_reg_3998;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        layer_out_i_d0 = trunc_ln708_263_reg_3988;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        layer_out_i_d0 = trunc_ln708_261_reg_3978;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        layer_out_i_d0 = trunc_ln708_259_reg_3968;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        layer_out_i_d0 = trunc_ln708_257_reg_3958;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        layer_out_i_d0 = trunc_ln708_255_reg_3948;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        layer_out_i_d0 = trunc_ln708_253_reg_3938;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        layer_out_i_d0 = trunc_ln708_251_reg_3928;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        layer_out_i_d0 = trunc_ln708_249_reg_3918;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        layer_out_i_d0 = trunc_ln708_247_reg_3908;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        layer_out_i_d0 = trunc_ln708_245_reg_3898;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        layer_out_i_d0 = trunc_ln708_243_reg_3888;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        layer_out_i_d0 = trunc_ln708_241_reg_3878;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        layer_out_i_d0 = trunc_ln708_239_reg_3868;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        layer_out_i_d0 = trunc_ln708_237_reg_3858;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        layer_out_i_d0 = trunc_ln708_235_reg_3848;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        layer_out_i_d0 = trunc_ln708_233_reg_3838;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        layer_out_i_d0 = trunc_ln708_231_reg_3828;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        layer_out_i_d0 = {{acc_V_0_0_reg_1455[22:7]}};
    end else begin
        layer_out_i_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        layer_out_i_d1 = trunc_ln708_276_reg_4053;
    end else if ((1'b1 == ap_CS_fsm_state29)) begin
        layer_out_i_d1 = trunc_ln708_274_reg_4043;
    end else if ((1'b1 == ap_CS_fsm_state28)) begin
        layer_out_i_d1 = trunc_ln708_272_reg_4033;
    end else if ((1'b1 == ap_CS_fsm_state27)) begin
        layer_out_i_d1 = trunc_ln708_270_reg_4023;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        layer_out_i_d1 = trunc_ln708_268_reg_4013;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        layer_out_i_d1 = trunc_ln708_266_reg_4003;
    end else if ((1'b1 == ap_CS_fsm_state24)) begin
        layer_out_i_d1 = trunc_ln708_264_reg_3993;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        layer_out_i_d1 = trunc_ln708_262_reg_3983;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        layer_out_i_d1 = trunc_ln708_260_reg_3973;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        layer_out_i_d1 = trunc_ln708_258_reg_3963;
    end else if ((1'b1 == ap_CS_fsm_state20)) begin
        layer_out_i_d1 = trunc_ln708_256_reg_3953;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        layer_out_i_d1 = trunc_ln708_254_reg_3943;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        layer_out_i_d1 = trunc_ln708_252_reg_3933;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        layer_out_i_d1 = trunc_ln708_250_reg_3923;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        layer_out_i_d1 = trunc_ln708_248_reg_3913;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        layer_out_i_d1 = trunc_ln708_246_reg_3903;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        layer_out_i_d1 = trunc_ln708_244_reg_3893;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        layer_out_i_d1 = trunc_ln708_242_reg_3883;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        layer_out_i_d1 = trunc_ln708_240_reg_3873;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        layer_out_i_d1 = trunc_ln708_238_reg_3863;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        layer_out_i_d1 = trunc_ln708_236_reg_3853;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        layer_out_i_d1 = trunc_ln708_234_reg_3843;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        layer_out_i_d1 = trunc_ln708_232_reg_3833;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        layer_out_i_d1 = {{acc_V_1_0_reg_1443[22:7]}};
    end else begin
        layer_out_i_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state7))) begin
        layer_out_i_we0 = 1'b1;
    end else begin
        layer_out_i_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state28) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state7))) begin
        layer_out_i_we1 = 1'b1;
    end else begin
        layer_out_i_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        res_V_V_blk_n = res_V_V_full_n;
    end else begin
        res_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state32))) begin
        res_V_V_write = 1'b1;
    end else begin
        res_V_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state3) & (icmp_ln315_fu_1521_p2 == 1'd0))) begin
        tmpdata_V_address0 = zext_ln317_fu_1533_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        tmpdata_V_address0 = grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_data_V_address0;
    end else begin
        tmpdata_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((~((data_V_V_empty_n == 1'b0) & (icmp_ln315_fu_1521_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln315_fu_1521_p2 == 1'd0))) begin
        tmpdata_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        tmpdata_V_ce0 = grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_data_V_ce0;
    end else begin
        tmpdata_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((data_V_V_empty_n == 1'b0) & (icmp_ln315_fu_1521_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln315_fu_1521_p2 == 1'd0))) begin
        tmpdata_V_we0 = 1'b1;
    end else begin
        tmpdata_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        w12_V_ce0 = 1'b1;
    end else begin
        w12_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (real_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln313_fu_1509_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if ((~((data_V_V_empty_n == 1'b0) & (icmp_ln315_fu_1521_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln315_fu_1521_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else if ((~((data_V_V_empty_n == 1'b0) & (icmp_ln315_fu_1521_p2 == 1'd0)) & (1'b1 == ap_CS_fsm_state3) & (icmp_ln315_fu_1521_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'd1 == and_ln326_12_fu_1610_p2) & (grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4) & (1'd0 == and_ln326_12_fu_1610_p2))) begin
                ap_NS_fsm = ap_ST_fsm_state31;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln324_fu_1616_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln324_fu_1616_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            if (((1'b1 == ap_CS_fsm_state31) & ((icmp_ln338_fu_2790_p2 == 1'd1) | (1'd0 == and_ln326_12_reg_3565)))) begin
                ap_NS_fsm = ap_ST_fsm_state33;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state32;
            end
        end
        ap_ST_fsm_state32 : begin
            if (((res_V_V_full_n == 1'b1) & (1'b1 == ap_CS_fsm_state32))) begin
                ap_NS_fsm = ap_ST_fsm_state31;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state32;
            end
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln354_fu_2858_p2 = (pY_5_load_reg_3553 + 32'd1);

assign add_ln356_fu_2869_p2 = (sY_5_load_reg_3543 + 32'd1);

assign add_ln359_fu_2812_p2 = (pX_5_load_reg_3559 + 32'd1);

assign add_ln361_fu_2823_p2 = (sX_5_load_reg_3533 + 32'd1);

assign and_ln326_11_fu_1604_p2 = (icmp_ln326_18_fu_1592_p2 & icmp_ln326_17_fu_1572_p2);

assign and_ln326_12_fu_1610_p2 = (and_ln326_fu_1598_p2 & and_ln326_11_fu_1604_p2);

assign and_ln326_fu_1598_p2 = (icmp_ln326_fu_1542_p2 & icmp_ln326_16_fu_1552_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd7];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (real_start == 1'b0));
end

always @ (*) begin
    ap_block_state3 = ((data_V_V_empty_n == 1'b0) & (icmp_ln315_fu_1521_p2 == 1'd0));
end

always @ (*) begin
    ap_block_state3_ignore_call0 = ((data_V_V_empty_n == 1'b0) & (icmp_ln315_fu_1521_p2 == 1'd0));
end

assign ap_block_state5_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_606 = (((icmp_ln346_fu_2807_p2 == 1'd1) & (icmp_ln350_fu_2853_p2 == 1'd0) & (1'd0 == and_ln326_12_reg_3565)) | ((icmp_ln346_fu_2807_p2 == 1'd1) & (icmp_ln338_fu_2790_p2 == 1'd1) & (icmp_ln350_fu_2853_p2 == 1'd0)));
end

always @ (*) begin
    ap_condition_743 = (((icmp_ln350_fu_2853_p2 == 1'd1) & (icmp_ln346_fu_2807_p2 == 1'd1) & (1'd0 == and_ln326_12_reg_3565)) | ((icmp_ln350_fu_2853_p2 == 1'd1) & (icmp_ln346_fu_2807_p2 == 1'd1) & (icmp_ln338_fu_2790_p2 == 1'd1)));
end

always @ (*) begin
    ap_condition_821 = (((icmp_ln346_fu_2807_p2 == 1'd0) & (1'd0 == and_ln326_12_reg_3565)) | ((icmp_ln338_fu_2790_p2 == 1'd1) & (icmp_ln346_fu_2807_p2 == 1'd0)));
end

always @ (*) begin
    ap_condition_823 = (((icmp_ln346_fu_2807_p2 == 1'd1) & (1'd0 == and_ln326_12_reg_3565)) | ((icmp_ln346_fu_2807_p2 == 1'd1) & (icmp_ln338_fu_2790_p2 == 1'd1)));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_ready = internal_ap_ready;

assign grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_start = grp_cnnshift_arr_ap_fixed_ap_fixed_16_4_5_3_0_config12_s_fu_1500_ap_start_reg;

assign grp_fu_2893_p1 = sext_ln1116_fu_1638_p1;

assign grp_fu_2901_p1 = sext_ln1116_fu_1638_p1;

assign grp_fu_2909_p1 = sext_ln1116_fu_1638_p1;

assign grp_fu_2917_p1 = sext_ln1116_fu_1638_p1;

assign grp_fu_2925_p1 = sext_ln1116_fu_1638_p1;

assign grp_fu_2933_p1 = sext_ln1116_fu_1638_p1;

assign grp_fu_2941_p1 = sext_ln1116_fu_1638_p1;

assign grp_fu_2949_p1 = sext_ln1116_fu_1638_p1;

assign grp_fu_2957_p1 = sext_ln1116_fu_1638_p1;

assign grp_fu_2965_p1 = sext_ln1116_fu_1638_p1;

assign grp_fu_2973_p1 = sext_ln1116_fu_1638_p1;

assign grp_fu_2981_p1 = sext_ln1116_fu_1638_p1;

assign grp_fu_2989_p1 = sext_ln1116_fu_1638_p1;

assign grp_fu_2997_p1 = sext_ln1116_fu_1638_p1;

assign grp_fu_3005_p1 = sext_ln1116_fu_1638_p1;

assign grp_fu_3013_p1 = sext_ln1116_fu_1638_p1;

assign grp_fu_3021_p1 = sext_ln1116_fu_1638_p1;

assign grp_fu_3029_p1 = sext_ln1116_fu_1638_p1;

assign grp_fu_3037_p1 = sext_ln1116_fu_1638_p1;

assign grp_fu_3045_p1 = sext_ln1116_fu_1638_p1;

assign grp_fu_3053_p1 = sext_ln1116_fu_1638_p1;

assign grp_fu_3061_p1 = sext_ln1116_fu_1638_p1;

assign grp_fu_3069_p1 = sext_ln1116_fu_1638_p1;

assign grp_fu_3077_p1 = sext_ln1116_fu_1638_p1;

assign grp_fu_3085_p1 = sext_ln1116_fu_1638_p1;

assign grp_fu_3093_p1 = sext_ln1116_fu_1638_p1;

assign grp_fu_3101_p1 = sext_ln1116_fu_1638_p1;

assign grp_fu_3109_p1 = sext_ln1116_fu_1638_p1;

assign grp_fu_3117_p1 = sext_ln1116_fu_1638_p1;

assign grp_fu_3125_p1 = sext_ln1116_fu_1638_p1;

assign grp_fu_3133_p1 = sext_ln1116_fu_1638_p1;

assign grp_fu_3141_p1 = sext_ln1116_fu_1638_p1;

assign grp_fu_3149_p1 = sext_ln1116_fu_1638_p1;

assign grp_fu_3157_p1 = sext_ln1116_fu_1638_p1;

assign grp_fu_3165_p1 = sext_ln1116_fu_1638_p1;

assign grp_fu_3173_p1 = sext_ln1116_fu_1638_p1;

assign grp_fu_3181_p1 = sext_ln1116_fu_1638_p1;

assign grp_fu_3189_p1 = sext_ln1116_fu_1638_p1;

assign grp_fu_3197_p1 = sext_ln1116_fu_1638_p1;

assign grp_fu_3205_p1 = sext_ln1116_fu_1638_p1;

assign grp_fu_3213_p1 = sext_ln1116_fu_1638_p1;

assign grp_fu_3221_p1 = sext_ln1116_fu_1638_p1;

assign grp_fu_3229_p1 = sext_ln1116_fu_1638_p1;

assign grp_fu_3237_p1 = sext_ln1116_fu_1638_p1;

assign grp_fu_3245_p1 = sext_ln1116_fu_1638_p1;

assign grp_fu_3253_p1 = sext_ln1116_fu_1638_p1;

assign grp_fu_3261_p1 = sext_ln1116_fu_1638_p1;

assign i1_fu_1527_p2 = (i1_0_i_reg_880 + 6'd1);

assign i_fu_1515_p2 = (i_0_i_reg_869 + 11'd1);

assign i_ic_fu_2796_p2 = (i_ic_0_i_reg_1478 + 6'd1);

assign icmp_ln313_fu_1509_p2 = ((i_0_i_reg_869 == 11'd1156) ? 1'b1 : 1'b0);

assign icmp_ln315_fu_1521_p2 = ((i1_0_i_reg_880 == 6'd48) ? 1'b1 : 1'b0);

assign icmp_ln324_fu_1616_p2 = ((in_index_reg_1467 == 9'd432) ? 1'b1 : 1'b0);

assign icmp_ln326_16_fu_1552_p2 = ((sY_5 == 32'd2) ? 1'b1 : 1'b0);

assign icmp_ln326_17_fu_1572_p2 = (($signed(tmp_13_fu_1562_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln326_18_fu_1592_p2 = (($signed(tmp_14_fu_1582_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln326_fu_1542_p2 = ((sX_5 == 32'd2) ? 1'b1 : 1'b0);

assign icmp_ln338_fu_2790_p2 = ((i_ic_0_i_reg_1478 == 6'd48) ? 1'b1 : 1'b0);

assign icmp_ln346_fu_2807_p2 = ((pX_5_load_reg_3559 == 32'd33) ? 1'b1 : 1'b0);

assign icmp_ln350_fu_2853_p2 = ((pY_5_load_reg_3553 == 32'd33) ? 1'b1 : 1'b0);

assign ir_fu_1622_p2 = (in_index_reg_1467 + 9'd1);

assign res_V_V_din = layer_out_i_q0;

assign select_ln356_fu_2874_p3 = ((icmp_ln326_16_reg_3548[0:0] === 1'b1) ? 32'd2 : add_ln356_fu_2869_p2);

assign select_ln361_fu_2828_p3 = ((icmp_ln326_reg_3538[0:0] === 1'b1) ? 32'd2 : add_ln361_fu_2823_p2);

assign sext_ln1116_fu_1638_p0 = layer_in_V_q0;

assign sext_ln1116_fu_1638_p1 = sext_ln1116_fu_1638_p0;

assign start_out = real_start;

assign tmp_13_fu_1562_p4 = {{pY_5[31:1]}};

assign tmp_14_fu_1582_p4 = {{pX_5[31:1]}};

assign tmp_283_fu_1650_p4 = {{w12_V_q0[15:8]}};

assign tmp_284_fu_1664_p4 = {{w12_V_q0[23:16]}};

assign tmp_285_fu_1678_p4 = {{w12_V_q0[31:24]}};

assign tmp_286_fu_1692_p4 = {{w12_V_q0[39:32]}};

assign tmp_287_fu_1706_p4 = {{w12_V_q0[47:40]}};

assign tmp_288_fu_1720_p4 = {{w12_V_q0[55:48]}};

assign tmp_289_fu_1734_p4 = {{w12_V_q0[63:56]}};

assign tmp_290_fu_1748_p4 = {{w12_V_q0[71:64]}};

assign tmp_291_fu_1762_p4 = {{w12_V_q0[79:72]}};

assign tmp_292_fu_1776_p4 = {{w12_V_q0[87:80]}};

assign tmp_293_fu_1790_p4 = {{w12_V_q0[95:88]}};

assign tmp_294_fu_1804_p4 = {{w12_V_q0[103:96]}};

assign tmp_295_fu_1818_p4 = {{w12_V_q0[111:104]}};

assign tmp_296_fu_1832_p4 = {{w12_V_q0[119:112]}};

assign tmp_297_fu_1846_p4 = {{w12_V_q0[127:120]}};

assign tmp_298_fu_1860_p4 = {{w12_V_q0[135:128]}};

assign tmp_299_fu_1874_p4 = {{w12_V_q0[143:136]}};

assign tmp_300_fu_1888_p4 = {{w12_V_q0[151:144]}};

assign tmp_301_fu_1902_p4 = {{w12_V_q0[159:152]}};

assign tmp_302_fu_1916_p4 = {{w12_V_q0[167:160]}};

assign tmp_303_fu_1930_p4 = {{w12_V_q0[175:168]}};

assign tmp_304_fu_1944_p4 = {{w12_V_q0[183:176]}};

assign tmp_305_fu_1958_p4 = {{w12_V_q0[191:184]}};

assign tmp_306_fu_1972_p4 = {{w12_V_q0[199:192]}};

assign tmp_307_fu_1986_p4 = {{w12_V_q0[207:200]}};

assign tmp_308_fu_2000_p4 = {{w12_V_q0[215:208]}};

assign tmp_309_fu_2014_p4 = {{w12_V_q0[223:216]}};

assign tmp_310_fu_2028_p4 = {{w12_V_q0[231:224]}};

assign tmp_311_fu_2042_p4 = {{w12_V_q0[239:232]}};

assign tmp_312_fu_2056_p4 = {{w12_V_q0[247:240]}};

assign tmp_313_fu_2070_p4 = {{w12_V_q0[255:248]}};

assign tmp_314_fu_2084_p4 = {{w12_V_q0[263:256]}};

assign tmp_315_fu_2098_p4 = {{w12_V_q0[271:264]}};

assign tmp_316_fu_2112_p4 = {{w12_V_q0[279:272]}};

assign tmp_317_fu_2126_p4 = {{w12_V_q0[287:280]}};

assign tmp_318_fu_2140_p4 = {{w12_V_q0[295:288]}};

assign tmp_319_fu_2154_p4 = {{w12_V_q0[303:296]}};

assign tmp_320_fu_2168_p4 = {{w12_V_q0[311:304]}};

assign tmp_321_fu_2182_p4 = {{w12_V_q0[319:312]}};

assign tmp_322_fu_2196_p4 = {{w12_V_q0[327:320]}};

assign tmp_323_fu_2210_p4 = {{w12_V_q0[335:328]}};

assign tmp_324_fu_2224_p4 = {{w12_V_q0[343:336]}};

assign tmp_325_fu_2238_p4 = {{w12_V_q0[351:344]}};

assign tmp_326_fu_2252_p4 = {{w12_V_q0[359:352]}};

assign tmp_327_fu_2266_p4 = {{w12_V_q0[367:360]}};

assign tmp_328_fu_2280_p4 = {{w12_V_q0[375:368]}};

assign tmp_7_fu_2294_p4 = {{w12_V_q0[380:376]}};

assign trunc_ln332_fu_1634_p1 = w12_V_q0[7:0];

assign w12_V_address0 = zext_ln332_fu_1628_p1;

assign zext_ln317_fu_1533_p1 = i1_0_i_reg_880;

assign zext_ln332_fu_1628_p1 = in_index_reg_1467;

assign zext_ln340_fu_2802_p1 = i_ic_0_i_reg_1478;

endmodule //conv_2d_cl_ss_ap_fixed_ap_fixed_16_4_5_3_0_config12_s
